import 'package:fantasy_odyssey/Models/history_event.dart';
import 'package:fantasy_odyssey/Models/phase.dart';

class BagEndToRivendell {
  final events = [
    HistoryEvent(Phase.bagEndToRivendell, 0.2, "Leave Bag End at full dark (ca. 7 p.m.). Go around (W) end, jump hedge."),
    HistoryEvent(Phase.bagEndToRivendell, 1.6, "Go through gate into a lane. Head west."),
    HistoryEvent(Phase.bagEndToRivendell, 3.2, "Leave lane, follow hedgerows south."),
    HistoryEvent(Phase.bagEndToRivendell, 4.8, "Cross The Water on a plank bridge."),
    HistoryEvent(Phase.bagEndToRivendell, 8.0, "Cross The Great Road from the Brandywine Bridge. Enter Tookland."),
    HistoryEvent(Phase.bagEndToRivendell, 12.1, "Look back at lights of Hobbiton from first slopes of the Green Hill Country."),
    HistoryEvent(Phase.bagEndToRivendell, 14.5, "Hobbiton hidden as slopes rise and fall."),
    HistoryEvent(Phase.bagEndToRivendell, 17.7, "Stop in a birch grove. Eat a frugal supper (ca. 10 p.m.)."),
    HistoryEvent(Phase.bagEndToRivendell, 23.3, "Reach Stock Road."),
    HistoryEvent(Phase.bagEndToRivendell, 24.9, "Begin to sing. Walk through a deeply cloven track between tall trees."),
    HistoryEvent(Phase.bagEndToRivendell, 28.2, "Climb a steep slope. Pippins yawns (Nearly midnight)."),
    HistoryEvent(Phase.bagEndToRivendell, 29.0, "Camp - In a firwood just over top of the hill. Sleep by a large tree. Fox sees them."),
    HistoryEvent(Phase.bagEndToRivendell, 29.1, "Eat at campsite. Water from a stream at the foot of the hill. A little fall where the water fell a few feet over an outcrop of grey stone. After 10:00 a.m. when leave."),
    HistoryEvent(Phase.bagEndToRivendell, 38.6, "Road rolls up and down."),
    HistoryEvent(Phase.bagEndToRivendell, 46.7, "Road zig-zigs to top of a steep bank and goes down for the last time. Can see across Woody End to the River. Sun was beginning to get low as they went down the hill."),
    HistoryEvent(Phase.bagEndToRivendell, 51.5, "Road ahead runs fairly straight and level. Behind them it curves slightly. BLACK RIDER. Sam and Pippin hide in a hollow. Frodo behind tree by road (ca.5 p.m.)."),
    HistoryEvent(Phase.bagEndToRivendell, 56.3, "Keep a stones throw left of the road...slower going."),
    HistoryEvent(Phase.bagEndToRivendell, 59.5, "Road splits. Road to Stock bends left and goes down into the lowlands. They take a lane which branches to the right, winding through a wood of ancient Oaks. Sun down and evening coming on (ca. 6:30 p.m.). Quite close to the road-meeting they creep inside a huge tree. Eat and rest."),
    HistoryEvent(Phase.bagEndToRivendell, 61.2, "Go on in twilight. Begin to sing. (ca. 7:00 p.m.)"),
    HistoryEvent(Phase.bagEndToRivendell, 66.0, "And NOW to bed! Pippin says, when BLACK RIDER is heard again (ca. 9 p.m.). ELVES arrive, RIDER leaves, and Frodo & Co. continue with Elves."),
    HistoryEvent(Phase.bagEndToRivendell, 69.2, "Wood more dense, and lane went lower, running in a fold of hills, with hazel on the slopes alongside. Pippin quickly becomes sleepy."),
    HistoryEvent(Phase.bagEndToRivendell, 72.4, "Turn right off the path on a green ride through thickets."),
    HistoryEvent(Phase.bagEndToRivendell, 74.0, "Camp - Woody End. A green floor in the wood, roofed by boughs of trees. To the east a steep shoulder falls, and they can overlook the river valley. The lights of the village of Woodhall seen below (ca. 11 p.m.)."),
    HistoryEvent(Phase.bagEndToRivendell, 74.2, "Sleep late (leaving time ca. 11:00 a.m.). Frodo decides to cut SE to Buckleberry Ferry. Scramble down hill into the thick trees below. It begins to cloud up."),
    HistoryEvent(Phase.bagEndToRivendell, 75.6, "A deep-banked stream below the hill cuts across their path. Looking back, they see a Black Rider on the hillcrest where they had camped. They force through the bushes alongside the stream."),
    HistoryEvent(Phase.bagEndToRivendell, 77.2, "Pippin realizes it is the Stock-brook. The banks are low enough now for them to cross. The land on its south bank is wet and reedy."),
    HistoryEvent(Phase.bagEndToRivendell, 80.5, "They reach a belt of trees, mostly oaks with a few elms and ash. Drops of rain fall."),
    HistoryEvent(Phase.bagEndToRivendell, 83.7, "Pippin realizes they've turned too far south as they are still in the trees."),
    HistoryEvent(Phase.bagEndToRivendell, 86.9, "Still in the trees, they stop for lunch (ca. 2:00 p.m.). Their singing is cut by the cry of a Black Rider, and they leave (ca. 3:00 p.m.)."),
    HistoryEvent(Phase.bagEndToRivendell, 88.5, "Wood ends. The land steadily becomes more tame. Sun is shining brightly."),
    HistoryEvent(Phase.bagEndToRivendell, 90.1, "Reach area of the Marish with fields, meadows, hedges, gates, and drainage dikes."),
    HistoryEvent(Phase.bagEndToRivendell, 98.2, "Edges of fields worked by Farmer Maggot."),
    HistoryEvent(Phase.bagEndToRivendell, 99.8, "After a turnip field there is a stout gate to a rutted lane, edged by hedges."),
    HistoryEvent(Phase.bagEndToRivendell, 101.4, "Farmer Maggot's house and buildings: brick with thatched roofs, surrounded by a high wall cut by a wooden gate from the lane. Eat. (Est. time there: 5:30 - 7:00 p.m.: full dark when they leave)."),
    HistoryEvent(Phase.bagEndToRivendell, 104.6, "Farmer Maggot's lane meets the Causeway to Buckleberry Ferry. Ride in wagon."),
    HistoryEvent(Phase.bagEndToRivendell, 112.7, "Boggy land all around. Foggy. Merry meets them at the Ferry landing. As they reach the other side of the river, they can see a Black Rider on the west shore."),
    HistoryEvent(Phase.bagEndToRivendell, 113.5, "Taking the main road north from the Ferry, Buck Hill is on the left and Buckleberry on the right. They take a lane to the right, and climb up and down into the country."),
    HistoryEvent(Phase.bagEndToRivendell, 117.5, "Crickhollow - spend the night. A Conspiracy Unmasked."),
    HistoryEvent(Phase.bagEndToRivendell, 117.6, "Leave Crickhollow soon after 6:00 a.m. Foggy. Ride ponies slowly."),
    HistoryEvent(Phase.bagEndToRivendell, 120.7, "Enter tunnel under Hedge to reach The Old Forest. Path disappears (ca. 7:15 a.m.)."),
    HistoryEvent(Phase.bagEndToRivendell, 125.5, "The Bonfire Glade - clear path beyond. Sunny, but not yet in clearing (ca. 8 a.m.)."),
    HistoryEvent(Phase.bagEndToRivendell, 132.0, "On path in the Forest. Path climbs gently."),
    HistoryEvent(Phase.bagEndToRivendell, 140.0, "Top of knoll in Forest. Hazy. Surrounded by Trees. Eat, rest (11 a.m.-ca.1 p.m.)."),
    HistoryEvent(Phase.bagEndToRivendell, 141.6, "Path veers SE. Company leaves path and tries to turn north."),
    HistoryEvent(Phase.bagEndToRivendell, 144.0, "Cross series of deep folds running SE. Keep turning east. Lose direction."),
    HistoryEvent(Phase.bagEndToRivendell, 146.5, "Enter fold too deep to leave. Follow it SE to Withywindle (ca. 4 p.m.)."),
    HistoryEvent(Phase.bagEndToRivendell, 149.7, "Merry finds path along bank of the River. Follow it east through wetlands."),
    HistoryEvent(Phase.bagEndToRivendell, 152.9, "Stop by Old Man Willow to rest. (ca. 5:30) Rescued by Tom Bombadil (ca.6:00 p.m.)."),
    HistoryEvent(Phase.bagEndToRivendell, 157.7, "Reach Tom Bombadil's house. Stars are out (ca. 7 p.m.)."),
    HistoryEvent(Phase.bagEndToRivendell, 157.9, "Rainy. Spend the day at Tom Bombadil's house."),
    HistoryEvent(Phase.bagEndToRivendell, 158.0, "Leave Tom's house and climb zig-zag path to brow of hill on west side of Barrow-downs (ca. 9 a.m.). On ponies go up steep slopes and down long limbs. No trees or water. Turn more east than they intend and enter the Barrow-downs, a place of great dread: inhabited by evil Barrow-wights from Angmar (R. Foster)."),
    HistoryEvent(Phase.bagEndToRivendell, 180.2, "Midday. Stop in a hollow atop a hill. Eat and fall asleep. Wake in fog, sun sinking."),
    HistoryEvent(Phase.bagEndToRivendell, 185.1, "Try to head north, but lose their way and become separated. Captured by Wights."),
    HistoryEvent(Phase.bagEndToRivendell, 185.2, "Frodo sings, Tom rescues and recalls ponies. Leave about 10 a.m. Tom leads."),
    HistoryEvent(Phase.bagEndToRivendell, 189.9, "Ride north through a gap."),
    HistoryEvent(Phase.bagEndToRivendell, 197.9, "Reach dike and hedge. Former boundary of Cardolan, part of the North Kingdom of Arnor."),
    HistoryEvent(Phase.bagEndToRivendell, 210.8, "Return to Great East Road (ca.5:30). Tom departs. Strider sees them, but hides."),
    HistoryEvent(Phase.bagEndToRivendell, 217.3, "Reach Bree. Stay at The Prancing Pony. Meet Strider. Ponies stolen during night."),
    HistoryEvent(Phase.bagEndToRivendell, 217.4, "Leave Bree on East Road (ca. 9:30 a.m.)."),
    HistoryEvent(Phase.bagEndToRivendell, 225.3, "Leave road and head north into Chetwood. No living things all day."),
    HistoryEvent(Phase.bagEndToRivendell, 236.6, "Camp in Chetwood, east of Archet."),
    HistoryEvent(Phase.bagEndToRivendell, 236.7, "Head east. Ground dropping slowly. Quiet and peaceful."),
    HistoryEvent(Phase.bagEndToRivendell, 262.3, "Camp in eastern Chetwood."),
    HistoryEvent(Phase.bagEndToRivendell, 265.5, "Come out of the Chetwood."),
    HistoryEvent(Phase.bagEndToRivendell, 278.4, "Ground becomes damp. Entering western edge of Midgewater Marshes."),
    HistoryEvent(Phase.bagEndToRivendell, 288.1, "Camp in western part of the Marshes."),
    HistoryEvent(Phase.bagEndToRivendell, 312.2, "Camp in eastern part of the Marshes. See flashes of light in the east during the night (Gandalf on Weathertop)."),
    HistoryEvent(Phase.bagEndToRivendell, 318.7, "Reach eastern edge of the Marshes. Can see Weather Hills ahead. Land starts to rise. Land drier and very barren. A few birds."),
    HistoryEvent(Phase.bagEndToRivendell, 339.6, "Camp by a stream, among stunted alder trees. Moon waxing."),
    HistoryEvent(Phase.bagEndToRivendell, 339.7, "Frost. Very clear. Can see crumbled ruins on Hills ahead."),
    HistoryEvent(Phase.bagEndToRivendell, 368.5, "Reach foot of the Weather Hills. Camp there."),
    HistoryEvent(Phase.bagEndToRivendell, 368.7, "Follow path south toward Weathertop: path is cunningly hidden and is edged with stones where land is open. Sam recites part of The Fall of Gil-galad."),
    HistoryEvent(Phase.bagEndToRivendell, 384.6, "Midday - Near south end of path. Reach dell at western foot of hill."),
    HistoryEvent(Phase.bagEndToRivendell, 386.2, "Climb to top of Weathertop and enter the ruins of the watch Tower of Amon. See Black Riders on road below."),
    HistoryEvent(Phase.bagEndToRivendell, 387.9, "Return to dell. Camp there. Attack of Nazgul at night."),
    HistoryEvent(Phase.bagEndToRivendell, 388.0, "Injured, Frodo is carried on pony. Head south from dell."),
    HistoryEvent(Phase.bagEndToRivendell, 403.9, "Cross Great East Road and enter thickets on south side. Land slopes south."),
    HistoryEvent(Phase.bagEndToRivendell, 418.4, "Camp in thickets."),
    HistoryEvent(Phase.bagEndToRivendell, 449.0, "Camp."),
    HistoryEvent(Phase.bagEndToRivendell, 479.6, "Camp - Follow a wide shallow curving valley."),
    HistoryEvent(Phase.bagEndToRivendell, 510.2, "Camp - Continue in valley."),
    HistoryEvent(Phase.bagEndToRivendell, 540.7, "Continue in valley. Land starts to rise. Can see huddle of hills ahead."),
    HistoryEvent(Phase.bagEndToRivendell, 571.3, "Camp not far SW of bridge. Camp is high enough for Merry to see the Loudwater far in the distance!"),
    HistoryEvent(Phase.bagEndToRivendell, 572.9, "Return to The Great East Road."),
    HistoryEvent(Phase.bagEndToRivendell, 576.1, "Strider scouts ahead and finds an elf-stone on The Last Bridge. He believes it is a token of safety. Company crosses the River Hoarwell/Mitheithel."),
    HistoryEvent(Phase.bagEndToRivendell, 577.8, "Turn north from the Road. Enter the steep lands of the Trollshaws. They can see ruined walls and towers frowning down."),
    HistoryEvent(Phase.bagEndToRivendell, 582.6, "Hills quickly shut them in. Difficult going. Camp."),
    HistoryEvent(Phase.bagEndToRivendell, 592.2, "More climbing."),
    HistoryEvent(Phase.bagEndToRivendell, 601.9, "Weather turns wet during the day."),
    HistoryEvent(Phase.bagEndToRivendell, 611.6, "Hills higher and steeper. They are forced north out of their way. Still raining. Camp on a stony shelf by a shallow cave."),
    HistoryEvent(Phase.bagEndToRivendell, 621.2, "Rain stops. Strider scouts. Start late. Turn SE, scrambling over rocky ground. Find a valley, but it ends in a high ridge. Climb ridge and camp in a saddle at top. COLD. Build a fire under a gnarled pine."),
    HistoryEvent(Phase.bagEndToRivendell, 622.8, "Slope beyond ridge is much easier. Bright, fair day. Strider briefly sees the Loudwater/Bruinen in the distance."),
    HistoryEvent(Phase.bagEndToRivendell, 626.0, "Reach a trail."),
    HistoryEvent(Phase.bagEndToRivendell, 630.9, "Find Troll-hole. Continue on level path through woods."),
    HistoryEvent(Phase.bagEndToRivendell, 632.5, "Stone Trolls. Rest. Sam recites Old Troll. Continue in afternoon. Woods."),
    HistoryEvent(Phase.bagEndToRivendell, 643.7, "Return to the Road."),
    HistoryEvent(Phase.bagEndToRivendell, 651.8, "While looking for a place to camp, hear a horse: Glorfindel."),
    HistoryEvent(Phase.bagEndToRivendell, 675.9, "March all night. Frodo is on Glorfindels horse. Camp next to the road at dawn."),
    HistoryEvent(Phase.bagEndToRivendell, 676.1, "Camp less than 5 hours. Take road with 2 brief rests."),
    HistoryEvent(Phase.bagEndToRivendell, 690.4, "Cross a small stream. Rest stop."),
    HistoryEvent(Phase.bagEndToRivendell, 695.2, "Rest stop."),
    HistoryEvent(Phase.bagEndToRivendell, 708.1, "Camp where road bends right to run down slope toward the River Bruinen."),
    HistoryEvent(Phase.bagEndToRivendell, 708.3, "Leave early morning, hobbling along (ca. 7 a.m.)."),
    HistoryEvent(Phase.bagEndToRivendell, 719.4, "Road running downhill. Much grass on sides."),
    HistoryEvent(Phase.bagEndToRivendell, 722.6, "Road plunges through a cutting of red stone with tall pines. Glorfindel says Run!"),
    HistoryEvent(Phase.bagEndToRivendell, 723.4, "Hobbits are halfway across grassy flat when Nazgul burst through behind them."),
    HistoryEvent(Phase.bagEndToRivendell, 724.2, "Attack at the Ford (ca. noon). Glorfindels horse carries Frodo across Ford. Nazgul drown. Frodo falls."),
    HistoryEvent(Phase.bagEndToRivendell, 727.4, "Company meets Elves sent from Rivendell (est. 2 p.m.). They take Frodo ahead. Rest of company follows on foot."),
    HistoryEvent(Phase.bagEndToRivendell, 735.5, "Come to the sudden cliff into the valley of Rivendell."),
    HistoryEvent(Phase.bagEndToRivendell, 737.1, "Frodo reaches Rivendell carried by the Elves (est. 4 p.m.). Others arrive in evening."),
  ];
}