import '../history_event.dart';
import '../phase.dart';

class BagEndToGreyHavens {
  final events = [
    HistoryEvent(Phase.bagEndToGreyHavens, 5502.3, "Sam and Frodo leave Bag End during the morning: Frodo on his pony, Strider, and Sam on Bill. They go south on the lane into Hobbiton. Cross the bridge over The Water and turn west."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5504.0, "Follow lane west along The Water."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5507.2, "Come to the plank bridge over The Water: the way they had taken from Bag End during the Quest. Retracing their journey, they go south along a path."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5510.4, "Cross the Great East Road from the Brandywine Bridge. Enter Tookland."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5514.4, "Hobbiton can still be seen from first slopes of the Green Hill Country."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5516.8, "Hobbiton is hidden as slopes rise and fall."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5520.0, "Ride by a birch wood."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5525.7, "Reach Stock Road."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5527.3, "Ride through a deeply cloven track between tall trees."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5530.5, "Climb a steep slope."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5531.3, "Camp - In a firwood just over top of the hill. Sleep by a large tree."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5531.5, "They get water from the stream at the foot of the hill. “A little fall where the water fell a few feet over an outcrop of grey stone.”"),
    HistoryEvent(Phase.bagEndToGreyHavens, 5541.0, "Road rolls up and down."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5549.0, "Road zig-zigs to top of a steep bank and goes down for the last time. Can see across Woody End to the River. Continue on down the hill."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5553.8, "Road ahead runs fairly straight and level. Behind, it curves slightly. Sam points out the tree behind which Frodo had hidden from the Black Rider."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5561.9, "Stars are coming out as they reach the point where the road splits. The road to Stock bends left and goes down into the lowlands, while the path they took on their journey goes right, through ancient Oaks. Quite close to the road-meeting is the huge oak tree they had crept inside to eat. Standing beside it, they hear Elves singing: Galadriel, Celeborn, Elrond, and others appear on the valley road below, with Bilbo. Frodo and Sam join them."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5563.5, "The company takes the branching path a short distance, then turns southwest into the woods."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5566.7, "When they reach a woodland trail, they pass west through the woods, weaving through the Green-hill country. Continue all night."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5590.9, "Camp during the day at the south edge of the woods, still in the Green-hill country."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5591.0, "Continue west at dusk."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5607.0, "Pass south of Tuckburrow. Leave the hills and turn slightly more southwest."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5615.0, "Cross the road from Sarn Ford to Waymeet."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5631.1, "Pass now through open fields."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5647.2, "Camp in the open lands."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5647.3, "Continue southwest across open land."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5655.2, "Land begins to climb west toward the White Downs."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5663.3, "Cross the road from Hardbottle."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5671.3, "Skirt south of the higher hills of the White Downs. Turn more to the west."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5687.4, "Beyond the Downs are grassy lowlands, almost uninhabited."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5703.5, "Camp."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5703.7, "Curve now more north of west through grasslands."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5711.6, "Land slopes gently up toward the Far Downs."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5735.7, "Reach the crest of the Far Downs."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5737.3, "Zig-zag down the steep face of the Downs."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5743.7, "Reach the dry grasslands west of the Downs."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5759.8, "Can see the Tower Hills on the western horizon. Camp day and night."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5760.0, "Ride now during the day, through uninhabited lands."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5792.0, "Land begins to rise toward the Tower Hills."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5816.2, "Camp not far south of the Great East Road."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5816.3, "Continue northwest toward the Great East Road."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5824.2, "Reach the Great East Road. Turn west."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5832.3, "Road climbs the lowest slopes of the Tower Hills."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5856.4, "Road reaches the Towers at the crest of the hills. To the west they can see the waters of the Gulf of Lune. Continue downhill."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5872.5, "Camp just at the western feet of the Tower Hills."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5872.7, "Ride west on the Road toward the Grey Havens."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5888.6, "Land drops gently down toward the Gulf."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5904.7, "Land drops more rapidly and the waters are clearly visible to the horizon."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5912.7, "Begin to see towers of the Havens on both sides of the firth of Lune."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5919.2, "Reach the Gates of the south Haven. Are greeted by Círdan the Shipwright."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5920.8, "Reach the shore. See Gandalf and Shadowfax awaiting them. Merry and Pippin arrive as the party is boarding the White Ship. Frodo says farewell. End of the Fellowship of the Ring. The ship sails Into the West."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5920.9, "Sam, Merry and Pippin watch the ship as it passes out of sight, and remain watching far into the night."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5922.4, "At last they turn east and leave the Havens."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5924.0, "Go a short way on the Road and camp."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5924.2, "After breakfast, the hobbits ride east along the Road. Land rises steeply."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5936.9, "Slope becomes more gentle, but still climbs. Can see the top of the Towers ahead on the Tower Hills."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5969.1, "Camp at the feet of the Tower Hills (same site as the western journey)."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5969.2, "Road climbs the western slope of the Tower Hills."),
    HistoryEvent(Phase.bagEndToGreyHavens, 5985.2, "Reach the Towers on the crest of the Hills. Turn back for a last look west at the sea. Start down the eastern slope."),
    HistoryEvent(Phase.bagEndToGreyHavens, 6009.3, "Reach the foot of the Hills. Continue east on the Road. Road falls gently."),
    HistoryEvent(Phase.bagEndToGreyHavens, 6017.3, "Camp in grassland next to the Road."),
    HistoryEvent(Phase.bagEndToGreyHavens, 6017.5, "Continue through grassy plain. See no one."),
    HistoryEvent(Phase.bagEndToGreyHavens, 6049.5, "Ahead to the east, they can see the crest of the Far Downs."),
    HistoryEvent(Phase.bagEndToGreyHavens, 6065.6, "Camp just off the Road. Weather pleasant."),
    HistoryEvent(Phase.bagEndToGreyHavens, 6065.8, "Ride out early. Road curves east-northeast."),
    HistoryEvent(Phase.bagEndToGreyHavens, 6081.7, "Reach the steep western face of the Far Downs. The Road climbs through a long cutting with steep, rocky walls on each side."),
    HistoryEvent(Phase.bagEndToGreyHavens, 6084.9, "Road reaches the eastern end of the cutting. Now slopes gently down."),
    HistoryEvent(Phase.bagEndToGreyHavens, 6097.8, "Downlands gradually flow into the grassy lowlands to the east."),
    HistoryEvent(Phase.bagEndToGreyHavens, 6113.9, "Camp next to the Road."),
    HistoryEvent(Phase.bagEndToGreyHavens, 6114.1, "Early morning: continue east-northeast on road."),
    HistoryEvent(Phase.bagEndToGreyHavens, 6138.0, "Begin to see grazing lands."),
    HistoryEvent(Phase.bagEndToGreyHavens, 6154.1, "Reach the steep western face of the White Downs."),
    HistoryEvent(Phase.bagEndToGreyHavens, 6157.4, "Road rises sharply, cutting between chalky rock walls."),
    HistoryEvent(Phase.bagEndToGreyHavens, 6162.2, "Reach Michel Delving. Stay at an Inn."),
    HistoryEvent(Phase.bagEndToGreyHavens, 6162.3, "Leave after an early breakfast."),
    HistoryEvent(Phase.bagEndToGreyHavens, 6170.2, "Descend gentle east-running backslope. Can see many grazing lands and some cultivated fields in lowlands below."),
    HistoryEvent(Phase.bagEndToGreyHavens, 6178.3, "Reach the valleybottom east of the Downs. Road passes now through more settled area."),
    HistoryEvent(Phase.bagEndToGreyHavens, 6218.5, "Come to Waymeet. Stay at an Inn."),
    HistoryEvent(Phase.bagEndToGreyHavens, 6218.7, "Leave after a leisurely breakfast."),
    HistoryEvent(Phase.bagEndToGreyHavens, 6226.6, "To the south they can see the wooded hills of Tookland."),
    HistoryEvent(Phase.bagEndToGreyHavens, 6234.6, "Pass the pathway Sam and Frodo had taken south."),
    HistoryEvent(Phase.bagEndToGreyHavens, 6242.6, "Come to Bywater Road. Sam says farewell to Merry and Pippin. They continue east on the Road, singing as they go. Sam turns northwest on Bywater Road."),
    HistoryEvent(Phase.bagEndToGreyHavens, 6245.9, "Sam reaches Bywater and turns west toward Hobbiton."),
    HistoryEvent(Phase.bagEndToGreyHavens, 6253.6, "Sam comes to Hobbiton. Goes north over the bridge across the Water and climbs up the Hill."),
    HistoryEvent(Phase.bagEndToGreyHavens, 6253.9, "Sam arrives at Bag End at sunset: Home."),
  ];
}