import '../history_event.dart';
import '../phase.dart';

class IsengardToRivendell {
  final events = [
    HistoryEvent(Phase.isengardToRivendell, 3749.0, "Pass from the circle of Isengard. Follow the stone-paved road south."),
    HistoryEvent(Phase.isengardToRivendell, 3751.4, "All is green and growing."),
    HistoryEvent(Phase.isengardToRivendell, 3754.6, "Pass the sapling at the old pillar of the White Hand."),
    HistoryEvent(Phase.isengardToRivendell, 3757.8, "Stone pavement ends. Highway continues."),
    HistoryEvent(Phase.isengardToRivendell, 3764.3, "All around are newly planted trees and shrubs."),
    HistoryEvent(Phase.isengardToRivendell, 3770.7, "Leave the Wizard’s Vale."),
    HistoryEvent(Phase.isengardToRivendell, 3773.9, "Reach the campsite of the night before. Sunset. Final Separation: Aragorn and his knights ride on toward the Fords. Travellers turn west."),
    HistoryEvent(Phase.isengardToRivendell, 3775.5, "Camp in the dell next to the south-facing slope of Dol Baran, the last hill of the northern ranges. Here Pippin looked into the palantír."),
    HistoryEvent(Phase.isengardToRivendell, 3775.7, "Curve west from Dol Baran around the foothills of Methedras."),
    HistoryEvent(Phase.isengardToRivendell, 3820.6, "Camp. Still in the Gap of Rohan. White Mountains only ca. 50 miles south."),
    HistoryEvent(Phase.isengardToRivendell, 3820.7, "Continue west near foothills."),
    HistoryEvent(Phase.isengardToRivendell, 3844.7, "Turn slightly north. Open lands widen into wasted plains of Dunland."),
    HistoryEvent(Phase.isengardToRivendell, 3868.9, "Camp by a small stream."),
    HistoryEvent(Phase.isengardToRivendell, 3869.0, "Cross stream. Turn northwest."),
    HistoryEvent(Phase.isengardToRivendell, 3893.0, "Dunlendings see company and hide."),
    HistoryEvent(Phase.isengardToRivendell, 3917.1, "Camp at base of an out-thrust hill of Methedras."),
    HistoryEvent(Phase.isengardToRivendell, 3917.3, "Continue riding almost due north."),
    HistoryEvent(Phase.isengardToRivendell, 3926.8, "Cross a small stream."),
    HistoryEvent(Phase.isengardToRivendell, 3941.3, "Hills draw away to east. Wide plains lie west."),
    HistoryEvent(Phase.isengardToRivendell, 3965.4, "Reach the remains of the roadway to Tharbad. Camp."),
    HistoryEvent(Phase.isengardToRivendell, 3965.6, "Follow the old roadway northwest."),
    HistoryEvent(Phase.isengardToRivendell, 3989.6, "See woods in the distance across the roadway."),
    HistoryEvent(Phase.isengardToRivendell, 3997.6, "Snowcapped peak of Methedras rises due east."),
    HistoryEvent(Phase.isengardToRivendell, 4013.7, "Stop at a small stream. Woods lie to east and north. Camp."),
    HistoryEvent(Phase.isengardToRivendell, 4013.9, "Cross stream and enter the woods."),
    HistoryEvent(Phase.isengardToRivendell, 4029.8, "Woods extend further west, into a valley between two streams."),
    HistoryEvent(Phase.isengardToRivendell, 4045.9, "A root of Methedras reaches west toward the road."),
    HistoryEvent(Phase.isengardToRivendell, 4058.8, "Leave wood just before sunset. Overtake Saruman and Grima Wormtongue walking north also. Saruman turns west with Grima."),
    HistoryEvent(Phase.isengardToRivendell, 4062.0, "Company stops by a stream. Camp."),
    HistoryEvent(Phase.isengardToRivendell, 4062.1, "Cross stream. Enter Northern Dunland. Continue on roadway."),
    HistoryEvent(Phase.isengardToRivendell, 4086.1, "Empty land, though green and pleasant."),
    HistoryEvent(Phase.isengardToRivendell, 4110.3, "Camp."),
    HistoryEvent(Phase.isengardToRivendell, 4110.4, "Continue northwest on roadway."),
    HistoryEvent(Phase.isengardToRivendell, 4134.4, "Draw farther and farther from the mountains and foothills."),
    HistoryEvent(Phase.isengardToRivendell, 4158.5, "Camp."),
    HistoryEvent(Phase.isengardToRivendell, 4158.7, "Continue northwest on roadway."),
    HistoryEvent(Phase.isengardToRivendell, 4174.6, "Reach a point where the land drops into the valley of the Greyflood. Turn northeast from the roadway and follow the ridge of the upland shelf. Weather golden."),
    HistoryEvent(Phase.isengardToRivendell, 4206.8, "Camp in plains. Marshes of the Swanfleet lie to the north."),
    HistoryEvent(Phase.isengardToRivendell, 4207.0, "Continue northeast."),
    HistoryEvent(Phase.isengardToRivendell, 4231.0, "Continue to follow the eastern edge of the upland shelf."),
    HistoryEvent(Phase.isengardToRivendell, 4255.1, "Camp in plains. Silver night."),
    HistoryEvent(Phase.isengardToRivendell, 4255.3, "Continue northeast."),
    HistoryEvent(Phase.isengardToRivendell, 4271.2, "Can see mists above the fens of the Swanfleet delta."),
    HistoryEvent(Phase.isengardToRivendell, 4295.3, "Cross the ford of the Swanfleet. West of the ford are falls where the river descends from the upland shelf to the lowlands of the Greyflood, spreading in a broad inland delta."),
    HistoryEvent(Phase.isengardToRivendell, 4296.9, "Eregion – Turn east and follow the river."),
    HistoryEvent(Phase.isengardToRivendell, 4303.4, "Camp by river."),
    HistoryEvent(Phase.isengardToRivendell, 4303.5, "Continue east next to the river."),
    HistoryEvent(Phase.isengardToRivendell, 4351.7, "Reach the ruins of Ost-en-Edhil, the former chief city of the Elf-realm of Hollin/Eregion. Camp at the confluence of the Glanduin and the Sirannon."),
    HistoryEvent(Phase.isengardToRivendell, 4351.8, "Follow the Moria-road east on the north bank of the Sirannon."),
    HistoryEvent(Phase.isengardToRivendell, 4375.8, "Valley deepens. Road runs above the valleyway."),
    HistoryEvent(Phase.isengardToRivendell, 4399.9, "Camp."),
    HistoryEvent(Phase.isengardToRivendell, 4400.1, "Continue east on Moria-road. Mountains of Moria rise ahead of them."),
    HistoryEvent(Phase.isengardToRivendell, 4440.2, "Turn northeast from the road."),
    HistoryEvent(Phase.isengardToRivendell, 4456.3, "Reach the hill where the Fellowship had sheltered from the Warg attack. Camp."),
    HistoryEvent(Phase.isengardToRivendell, 4456.4, "Galadriel, Celeborn, and others from Lórien depart. Travel NE toward the Redhorn Gate. Others watch until see the flash of Galadriel’s ring. Gandalf and the hobbits start for Rivendell. Travel northwest from the hill."),
    HistoryEvent(Phase.isengardToRivendell, 4501.3, "Camp."),
    HistoryEvent(Phase.isengardToRivendell, 4501.5, "Continue northwest from the hill."),
    HistoryEvent(Phase.isengardToRivendell, 4512.6, "Open country. Gentle slopes, easier for the ponies."),
    HistoryEvent(Phase.isengardToRivendell, 4546.4, "Cross a small stream. Camp. Due east Caradhras glows in sunset."),
    HistoryEvent(Phase.isengardToRivendell, 4546.6, "Turn due north."),
    HistoryEvent(Phase.isengardToRivendell, 4585.0, "Reach the foot of Hollin Ridge. Begin to climb, angling west."),
    HistoryEvent(Phase.isengardToRivendell, 4593.1, "Camp atop Hollin Ridge among the large smooth towering rocks."),
    HistoryEvent(Phase.isengardToRivendell, 4593.2, "Start down the north side of the ridge. Thread their way between rocks."),
    HistoryEvent(Phase.isengardToRivendell, 4601.1, "Reach the base of the ridge. Turn northeast."),
    HistoryEvent(Phase.isengardToRivendell, 4617.2, "Cross a small stream."),
    HistoryEvent(Phase.isengardToRivendell, 4638.1, "Camp west of a hill."),
    HistoryEvent(Phase.isengardToRivendell, 4638.3, "Continue northeast."),
    HistoryEvent(Phase.isengardToRivendell, 4657.4, "Land becomes more rugged to the east."),
    HistoryEvent(Phase.isengardToRivendell, 4683.2, "Descend a slope to a small stream valley. Camp by stream."),
    HistoryEvent(Phase.isengardToRivendell, 4683.4, "Cross stream and ride east alongside it."),
    HistoryEvent(Phase.isengardToRivendell, 4684.8, "Climb out of stream valley. Continue northeast."),
    HistoryEvent(Phase.isengardToRivendell, 4705.7, "Reach crest of a hill. Start down at an angle."),
    HistoryEvent(Phase.isengardToRivendell, 4728.3, "Reach a small stream. Marshy area lies to the west. Camp."),
    HistoryEvent(Phase.isengardToRivendell, 4728.4, "Cross the stream and follow valley east-northeast."),
    HistoryEvent(Phase.isengardToRivendell, 4737.9, "Climb northeast up a slope. In the west, the marsh ends."),
    HistoryEvent(Phase.isengardToRivendell, 4754.0, "Turn north. Start downhill again."),
    HistoryEvent(Phase.isengardToRivendell, 4773.3, "Cross a small stream. Camp."),
    HistoryEvent(Phase.isengardToRivendell, 4773.5, "To the west the Loudwater/Bruinen now runs in a deep valley and the surrounding terrain is too rugged to cross easily. Turn northeast again."),
    HistoryEvent(Phase.isengardToRivendell, 4794.2, "Cross a small stream."),
    HistoryEvent(Phase.isengardToRivendell, 4818.4, "Cross a small stream. Camp."),
    HistoryEvent(Phase.isengardToRivendell, 4818.5, "Turn slightly west of north."),
    HistoryEvent(Phase.isengardToRivendell, 4850.6, "Reach Ford of Bruinen. Follow stone-marked path NE to Rivendell."),
    HistoryEvent(Phase.isengardToRivendell, 4861.8, "Come to the valley of Rivendell and descend zig-zag road."),
    HistoryEvent(Phase.isengardToRivendell, 4863.4, "Reach the Last Homely House."),
  ];
}