import '../history_event.dart';
import '../phase.dart';

class LothlorienToRauros {
  final events = [
    HistoryEvent(Phase.lothlorienToRauros, 1480.8, "Leave Caras Galadon after breakfast. Lembas, cloaks and rope are provided. Haldir guides the Fellowship south and east through rolling woodlands, which fall away toward the rivers."),
    HistoryEvent(Phase.lothlorienToRauros, 1496.7, "Noon – Reach grassy lawn on the Silverlode just west of the Anduin. Practice paddling. Meet swan-ship of Celeborn and Galadriel. Lunch and gift-giving. Leave in 3 small boats (ca. 1 p.m.)."),
    HistoryEvent(Phase.lothlorienToRauros, 1503.1, "DRIFT. Sweep around a bend, and high banks hide the light of Lórien."),
    HistoryEvent(Phase.lothlorienToRauros, 1519.2, "Bare woods on both banks. Land is silent. Misty. Dusk comes early."),
    HistoryEvent(Phase.lothlorienToRauros, 1530.5, "Camp in woods on west bank (ca. 8:30 p.m.). Dreary and cold."),
    HistoryEvent(Phase.lothlorienToRauros, 1530.6, "Leave early (ca. 7:30 a.m.). Bare trees continue on both sides. DRIFT. No enemies."),
    HistoryEvent(Phase.lothlorienToRauros, 1588.4, "Camp on west bank of the river."),
    HistoryEvent(Phase.lothlorienToRauros, 1588.6, "Leave early. DRIFT. No enemies."),
    HistoryEvent(Phase.lothlorienToRauros, 1622.2, "Trees thin. Gray and overcast."),
    HistoryEvent(Phase.lothlorienToRauros, 1641.5, "Trees disappear. Begin to see withered downs on east at the north edge of the Brown Lands. Tall reedy plains on west. Can see west to hills and mountains."),
    HistoryEvent(Phase.lothlorienToRauros, 1646.4, "Camp in flats north of the Field of Celebrant."),
    HistoryEvent(Phase.lothlorienToRauros, 1646.5, "Leave early. Feel urgency. Paddle all day."),
    HistoryEvent(Phase.lothlorienToRauros, 1673.7, "River broadens. Continues gray and overcast."),
    HistoryEvent(Phase.lothlorienToRauros, 1710.7, "Reach North Undeep with stony beaches on east – gravel shoals in the water: go carefully."),
    HistoryEvent(Phase.lothlorienToRauros, 1722.0, "River Limlight enters on west."),
    HistoryEvent(Phase.lothlorienToRauros, 1725.2, "High wolds of the Brown Lands on east. Downs seen on the west."),
    HistoryEvent(Phase.lothlorienToRauros, 1730.0, "Boromir mutters to himself. Just at dusk, Sam spots Gollum on a log."),
    HistoryEvent(Phase.lothlorienToRauros, 1742.9, "Camp on small eyot near western shore. Sam and Frodo watch. Gollum appears during Frodo’s watch. Aragorn wakes. Watches until morning."),
    HistoryEvent(Phase.lothlorienToRauros, 1743.1, "Leave early morning. Paddle long periods. Still overcast, east wind."),
    HistoryEvent(Phase.lothlorienToRauros, 1754.2, "River curves east. Wolds on both sides."),
    HistoryEvent(Phase.lothlorienToRauros, 1786.4, "River swings south. Still amid high hills."),
    HistoryEvent(Phase.lothlorienToRauros, 1805.7, "North edge of eastern South Undeep."),
    HistoryEvent(Phase.lothlorienToRauros, 1818.6, "Dusk. Continue through much of the night, paddling cautiously."),
    HistoryEvent(Phase.lothlorienToRauros, 1834.7, "Downs on far (east) bank. Hills of the Wold on near bank."),
    HistoryEvent(Phase.lothlorienToRauros, 1837.9, "Reach the north edge of western South Undeep."),
    HistoryEvent(Phase.lothlorienToRauros, 1850.7, "Reach steep north face of south downs, inner ridge – hidden in the dark."),
    HistoryEvent(Phase.lothlorienToRauros, 1858.8, "Camp during day. Downs on both sides of the river."),
    HistoryEvent(Phase.lothlorienToRauros, 1859.0, "Leave at dusk. Paddle cautiously. Sky clears. Sam notices ‘rind’ of the new Moon."),
    HistoryEvent(Phase.lothlorienToRauros, 1874.9, "North face of outer down ridge."),
    HistoryEvent(Phase.lothlorienToRauros, 1899.0, "Reach lowlands between downs and the Emyn Muil."),
    HistoryEvent(Phase.lothlorienToRauros, 1939.3, "Camp during day."),
    HistoryEvent(Phase.lothlorienToRauros, 1939.4, "Leave at dusk. Paddle cautiously."),
    HistoryEvent(Phase.lothlorienToRauros, 1947.3, "Banks grow stony. Hills north of the Emyn Muil rise on the east shore."),
    HistoryEvent(Phase.lothlorienToRauros, 1963.4, "Hills also appear on the west. The river passes through “low crumbling cliffs, and chimneys with grey weathered stone dark with ivy.”."),
    HistoryEvent(Phase.lothlorienToRauros, 1985.9, "They reach the higher Emyn Muil."),
    HistoryEvent(Phase.lothlorienToRauros, 2019.7, "Camp on west shore. Many birds circle during the day."),
    HistoryEvent(Phase.lothlorienToRauros, 2019.9, "Late in day Legolas sees eagle. Wait to full dark to leave (8:30 p.m.). Go slowly."),
    HistoryEvent(Phase.lothlorienToRauros, 2039.0, "Midnight. Sam hears racing water. North edge of the rapids of Sarn Gebir. ORC ATTACK. Reach western shore. Legolas shoots a Nazgul’s flying beast. Move upstream to a small shallow bay. Huddle in boats rest of the night."),
    HistoryEvent(Phase.lothlorienToRauros, 2042.3, "Foggy. Carry boats and packs to foot of rapids – 2 trips. Camp by pool that night."),
    HistoryEvent(Phase.lothlorienToRauros, 2042.4, "Leave at full light (ca. 7:30 a.m.)."),
    HistoryEvent(Phase.lothlorienToRauros, 2056.7, "Brief, heavy rain."),
    HistoryEvent(Phase.lothlorienToRauros, 2060.0, "They are in a wide ravine, with great rocky sides, and a few trees."),
    HistoryEvent(Phase.lothlorienToRauros, 2066.4, "Channel grows narrower and the River swifter."),
    HistoryEvent(Phase.lothlorienToRauros, 2072.8, "The Argonath. Boats are swept through the narrow gap between."),
    HistoryEvent(Phase.lothlorienToRauros, 2074.4, "Chasm of the Gates bends slightly to the west."),
    HistoryEvent(Phase.lothlorienToRauros, 2076.1, "Pass out of the chasm into the lake: Nen Hithoel. (ca. 2 p.m.)."),
    HistoryEvent(Phase.lothlorienToRauros, 2080.9, "Rest in boats and eat. Then paddle on."),
    HistoryEvent(Phase.lothlorienToRauros, 2101.8, "Aragorn leads them toward the west bank."),
    HistoryEvent(Phase.lothlorienToRauros, 2106.6, "Reach the lawn of Parth Galen below Amon Hen. “Rauros was calling with a great voice.” Camp there."),
  ];
}