import '../history_event.dart';
import '../phase.dart';

class MinasTirithToIsengard {
  final events = [
    HistoryEvent(Phase.minasTirithToIsengard, 2887.3, "Noon – Depart from the Gates of Minas Tirith. Merry rides on the wain, guarding the King’s arms. With them go all who remain of the Fellowship, as well as Queen Arwen, Elrond and his sons, Celeborn and Galadriel, and many knights of Gondor and Rohan."),
    HistoryEvent(Phase.minasTirithToIsengard, 2903.3, "Process through the Pelennor. Stop for the night at the gate of the Rammas Echor: the wall surrounding the Pelennor Fields."),
    HistoryEvent(Phase.minasTirithToIsengard, 2914.5, "Mt. Mindolluin is visible to the southwest, lit by the predawn glow."),
    HistoryEvent(Phase.minasTirithToIsengard, 2921.0, "The Grey Wood begins."),
    HistoryEvent(Phase.minasTirithToIsengard, 2930.6, "The Morgul Vale lies 35 miles due east."),
    HistoryEvent(Phase.minasTirithToIsengard, 2935.4, "Camp."),
    HistoryEvent(Phase.minasTirithToIsengard, 2943.5, "Thickets of the Grey Wood lie left of the road with Amon Dîn rising to the west of the Wood. Drums can be heard in the distance. King Aragorn’s heralds announce that the Forest of Drúadan is given to Ghân-buri-ghân and his folk and none may enter it without their leave."),
    HistoryEvent(Phase.minasTirithToIsengard, 2949.9, "Road curves more to the west around Amon Dîn."),
    HistoryEvent(Phase.minasTirithToIsengard, 2959.6, "The beacon hill Amon Dîn is 5 miles due south."),
    HistoryEvent(Phase.minasTirithToIsengard, 2967.6, "Camp by road north of the Drúadan Forest."),
    HistoryEvent(Phase.minasTirithToIsengard, 2972.5, "Road curves slightly to the north. Due east across the Anduin the peaks of the Ephel Dùath can be seen dark against the climbing sun."),
    HistoryEvent(Phase.minasTirithToIsengard, 2999.8, "Camp."),
    HistoryEvent(Phase.minasTirithToIsengard, 3004.6, "Eilenach beacon stands on a steep hill to the south, rising above the trees of Drúadan Forest."),
    HistoryEvent(Phase.minasTirithToIsengard, 3030.4, "Cross a small stream – the most eastern which empties into the delta of the Entwash. Along the Anduin the delta extends over 100 miles. The west edge of Drúadan Forest south of the road. Camp."),
    HistoryEvent(Phase.minasTirithToIsengard, 3049.7, "Pass the beacon on Nardol, the ‘Fire Hill.’"),
    HistoryEvent(Phase.minasTirithToIsengard, 3057.8, "Cross a small stream."),
    HistoryEvent(Phase.minasTirithToIsengard, 3064.2, "Camp."),
    HistoryEvent(Phase.minasTirithToIsengard, 3080.3, "The beacon hill of Erelas stands south of the road."),
    HistoryEvent(Phase.minasTirithToIsengard, 3096.4, "Camp."),
    HistoryEvent(Phase.minasTirithToIsengard, 3107.6, "High above to the south rise the sawtoothed tips of Rimmon – the highest peak in the eastern White Mountains: still snowcapped."),
    HistoryEvent(Phase.minasTirithToIsengard, 3123.7, "To the north the delta of the Entwash still stretches over 50 miles north to south. Rauros lies beyond, 100 miles away."),
    HistoryEvent(Phase.minasTirithToIsengard, 3128.6, "Camp."),
    HistoryEvent(Phase.minasTirithToIsengard, 3131.8, "Cross a small stream. The beacon hill of Minrimmon is on the left."),
    HistoryEvent(Phase.minasTirithToIsengard, 3149.5, "Cross a small stream."),
    HistoryEvent(Phase.minasTirithToIsengard, 3160.8, "Camp."),
    HistoryEvent(Phase.minasTirithToIsengard, 3178.5, "The beacon tower of Calenhad stands on a foothill of Calenhad peak."),
    HistoryEvent(Phase.minasTirithToIsengard, 3192.9, "Camp."),
    HistoryEvent(Phase.minasTirithToIsengard, 3196.2, "The peak above Calenhad rises to the left – still streaked with snow."),
    HistoryEvent(Phase.minasTirithToIsengard, 3209.0, "Cross a small stream."),
    HistoryEvent(Phase.minasTirithToIsengard, 3212.3, "Reach the edge of Firien Wood."),
    HistoryEvent(Phase.minasTirithToIsengard, 3225.1, "Camp in Firien Wood."),
    HistoryEvent(Phase.minasTirithToIsengard, 3230.0, "The Beacon of Halifirien lies left of the road on a hill which rises above the trees."),
    HistoryEvent(Phase.minasTirithToIsengard, 3247.7, "Cross the Mering Stream: Rohan. Enter the heart of the Firien Wood. This is the area called the ‘Fenmarch’ – a wet area, especially north of the road where the Entwash becomes sluggish and starts its spread outward into a delta."),
    HistoryEvent(Phase.minasTirithToIsengard, 3252.5, "Northeast across the plain (80 miles away) the East Wall of Rohan and the Western Emyn Muil can be seen."),
    HistoryEvent(Phase.minasTirithToIsengard, 3257.3, "Camp. Still among the trees."),
    HistoryEvent(Phase.minasTirithToIsengard, 3273.4, "South of the road the last of the great oak trees stand – end of Firien Wood."),
    HistoryEvent(Phase.minasTirithToIsengard, 3278.2, "Cross a small stream."),
    HistoryEvent(Phase.minasTirithToIsengard, 3289.5, "Camp."),
    HistoryEvent(Phase.minasTirithToIsengard, 3305.6, "Cross a small stream. The Fenmarch ends. Enter the area called the ‘Folde’, tucked against the hills, sheltered from the west and the south."),
    HistoryEvent(Phase.minasTirithToIsengard, 3316.9, "North of the road, the Entwash, flowing slowly in the level plains is choked with vegetation and is split into multiple braided channels."),
    HistoryEvent(Phase.minasTirithToIsengard, 3321.7, "Camp."),
    HistoryEvent(Phase.minasTirithToIsengard, 3337.8, "Cross a small stream. North across the Entwash the wide grassy Plains of Rohan lie green in the sun."),
    HistoryEvent(Phase.minasTirithToIsengard, 3355.5, "Cross a small stream. Camp."),
    HistoryEvent(Phase.minasTirithToIsengard, 3365.1, "Road turns more to the west."),
    HistoryEvent(Phase.minasTirithToIsengard, 3381.2, "Leave the Folde. A peak rises on the south – no longer snowcapped."),
    HistoryEvent(Phase.minasTirithToIsengard, 3386.1, "Camp."),
    HistoryEvent(Phase.minasTirithToIsengard, 3400.5, "Willow woods appear. Road turns more north, parallels the Entwash."),
    HistoryEvent(Phase.minasTirithToIsengard, 3413.4, "A wide willow thicket grows where the Snowbourne meets the Entwash, but narrows to scattered trees beside the road."),
    HistoryEvent(Phase.minasTirithToIsengard, 3418.2, "Camp."),
    HistoryEvent(Phase.minasTirithToIsengard, 3429.5, "Hills draw away to the south. Road continues through scattered willows."),
    HistoryEvent(Phase.minasTirithToIsengard, 3442.4, "The road curves northwest, hugging the foothills of Irensaga."),
    HistoryEvent(Phase.minasTirithToIsengard, 3450.4, "Camp."),
    HistoryEvent(Phase.minasTirithToIsengard, 3458.5, "The Snowbourne meanders through willow trees right of the road."),
    HistoryEvent(Phase.minasTirithToIsengard, 3461.7, "The road curves westerly around the mountain spur east of Edoras."),
    HistoryEvent(Phase.minasTirithToIsengard, 3464.9, "Reach field below the barrow mounds."),
    HistoryEvent(Phase.minasTirithToIsengard, 3466.5, "Climb to Meduseld in Edoras."),
    HistoryEvent(Phase.minasTirithToIsengard, 3466.7, "Leave Edoras. Turn west on the road to Helm’s Deep."),
    HistoryEvent(Phase.minasTirithToIsengard, 3468.1, "Ford the Snowbourne."),
    HistoryEvent(Phase.minasTirithToIsengard, 3505.2, "Cross a small stream."),
    HistoryEvent(Phase.minasTirithToIsengard, 3526.1, "Cross a small stream."),
    HistoryEvent(Phase.minasTirithToIsengard, 3543.8, "Cross a small stream. Camp."),
    HistoryEvent(Phase.minasTirithToIsengard, 3558.3, "Cross a small stream."),
    HistoryEvent(Phase.minasTirithToIsengard, 3569.5, "Cross a small stream."),
    HistoryEvent(Phase.minasTirithToIsengard, 3582.4, "Camp."),
    HistoryEvent(Phase.minasTirithToIsengard, 3590.4, "Cross a small stream."),
    HistoryEvent(Phase.minasTirithToIsengard, 3606.5, "Cross a small stream."),
    HistoryEvent(Phase.minasTirithToIsengard, 3621.0, "Camp."),
    HistoryEvent(Phase.minasTirithToIsengard, 3641.9, "Reach the road to the Deeping Coomb and Helm’s Deep. Turn south."),
    HistoryEvent(Phase.minasTirithToIsengard, 3651.6, "Climb upward through the Coomb."),
    HistoryEvent(Phase.minasTirithToIsengard, 3657.2, "Pass through Helm’s Dike."),
    HistoryEvent(Phase.minasTirithToIsengard, 3658.0, "Reach Helm’s Deep. Enter the Hornburg."),
    HistoryEvent(Phase.minasTirithToIsengard, 3658.2, "Leave Helm’s Deep."),
    HistoryEvent(Phase.minasTirithToIsengard, 3658.8, "Pass through Helm’s Dike. Ride down the Deeping Coomb."),
    HistoryEvent(Phase.minasTirithToIsengard, 3674.1, "Reach the beaten road and turn west to the Fords of Isen."),
    HistoryEvent(Phase.minasTirithToIsengard, 3683.8, "The peaks of the Thrihyrne rise to the south."),
    HistoryEvent(Phase.minasTirithToIsengard, 3698.3, "Cross the Fords of Isen. Pass the burial mound of Erkenbrand’s Riders."),
    HistoryEvent(Phase.minasTirithToIsengard, 3699.9, "Turn north on the highway to Isengard."),
    HistoryEvent(Phase.minasTirithToIsengard, 3722.4, "Camp 15 miles north of the Fords."),
    HistoryEvent(Phase.minasTirithToIsengard, 3725.6, "Enter the south end of the Wizard’s Vale."),
    HistoryEvent(Phase.minasTirithToIsengard, 3732.1, "All around are newly planted trees and shrubs."),
    HistoryEvent(Phase.minasTirithToIsengard, 3738.5, "Highway becomes a wide street, paved with stones."),
    HistoryEvent(Phase.minasTirithToIsengard, 3741.7, "The rubble from pillar of the White Hand now surrounds a sapling."),
    HistoryEvent(Phase.minasTirithToIsengard, 3744.9, "All is green and growing."),
    HistoryEvent(Phase.minasTirithToIsengard, 3747.4, "Reach the circle of Isengard, but the stone-circle is gone. A tall tree stands on each side of the old gateway, with a green path to Orthanc."),
    HistoryEvent(Phase.minasTirithToIsengard, 3748.2, "Saruman’s Isengard is no more. The Ents have transformed it into the Treegarth of Orthanc. The Tower rises from a mirroring lake, with an east-running stream feeding the Isen. All the circle is filled with trees and orchards. Treebeard tells Gandalf of Saruman’s release. Legolas and Gimli say farewell, and turn east to go home via Fangorn Forest."),
  ];
}