import '../history_event.dart';
import '../phase.dart';

class RaurosToMountDoom {
  final events = [
    HistoryEvent(Phase.raurosToMountDoom, 2106.8, "Breaking of the Fellowship. Noon. Frodo decides to go to Mordor alone, but Sam guesses. Reaches lake as Frodo is leaving. They go together."),
    HistoryEvent(Phase.raurosToMountDoom, 2107.0, "Paddle past the south end of Tol Brandir."),
    HistoryEvent(Phase.raurosToMountDoom, 2107.4, "Reach shelving shore on the south slopes of Amon Lhaw. Hide boat."),
    HistoryEvent(Phase.raurosToMountDoom, 2108.2, "Head SE into the “strange twisted knot of hills” – the eastern Emyn Muil."),
    HistoryEvent(Phase.raurosToMountDoom, 2109.8, "Reach south edge of the hills: “a sheer, high, impassible cliff overlooking the marshland of Nindalf ‘the Wetwang’, which lies East of the Anduin all along the delta of the Entwash."),
    HistoryEvent(Phase.raurosToMountDoom, 2111.5, "Turn north away from the cliff."),
    HistoryEvent(Phase.raurosToMountDoom, 2114.7, "Wind around a ravine."),
    HistoryEvent(Phase.raurosToMountDoom, 2119.5, "Reach steep east face of inner hills. Climb down."),
    HistoryEvent(Phase.raurosToMountDoom, 2122.7, "Camp about dusk. Hide behind boulders just back from the south-facing cliff. See glow of Gollum’s eyes."),
    HistoryEvent(Phase.raurosToMountDoom, 2122.9, "Leave at dawn."),
    HistoryEvent(Phase.raurosToMountDoom, 2129.2, "Climb into a gully and out. Forced to turn more to the north."),
    HistoryEvent(Phase.raurosToMountDoom, 2138.8, "Keep as close to the cliff as can, angling southeast. Stop to eat."),
    HistoryEvent(Phase.raurosToMountDoom, 2145.3, "Cliff curves more to the east."),
    HistoryEvent(Phase.raurosToMountDoom, 2148.5, "Enter another ravine. Cliff still too high to descend."),
    HistoryEvent(Phase.raurosToMountDoom, 2154.9, "Climb into another ravine. Camp at dusk."),
    HistoryEvent(Phase.raurosToMountDoom, 2155.1, "Leave at dawn."),
    HistoryEvent(Phase.raurosToMountDoom, 2158.1, "Cliff begins to curve much more to the north. The Wetwang curves south."),
    HistoryEvent(Phase.raurosToMountDoom, 2163.0, "Another ravine."),
    HistoryEvent(Phase.raurosToMountDoom, 2166.2, "Wind around rough area, forced back, away from cliff."),
    HistoryEvent(Phase.raurosToMountDoom, 2171.0, "Continue in barren, rugged hills – not even grass. Stop to eat."),
    HistoryEvent(Phase.raurosToMountDoom, 2175.8, "Zig-zag into ravine. The south edge of the Dead Marshes appear east of the tumbled lands below."),
    HistoryEvent(Phase.raurosToMountDoom, 2182.3, "Get lost in ravine. Realize they are “going in circles.” Runoff from the ravine goes to the marshes."),
    HistoryEvent(Phase.raurosToMountDoom, 2187.1, "Climb down to the bottom of another ravine. Cliff still too steep and high. Look out toward Mordor. Can smell the Dead Marshes. Go further back. Camp in a stony hollow surrounded by “great jagged pinnacles of weathered rock.” Cold."),
    HistoryEvent(Phase.raurosToMountDoom, 2187.3, "Leave at dawn. Cliff has now turned almost due north."),
    HistoryEvent(Phase.raurosToMountDoom, 2190.3, "Go close to the cliff, in hopes of seeing a way down."),
    HistoryEvent(Phase.raurosToMountDoom, 2191.9, "Must swing far back, then east again. Stop to listen for signs of Gollum."),
    HistoryEvent(Phase.raurosToMountDoom, 2193.5, "Return to cliff-top, but rough “scored and weathered rock” forces them away."),
    HistoryEvent(Phase.raurosToMountDoom, 2200.0, "Cliff face is now lower, but they do not notice as they are not by the edge. Scramble into a deep cleft and out again."),
    HistoryEvent(Phase.raurosToMountDoom, 2204.8, "Stop briefly. Eat."),
    HistoryEvent(Phase.raurosToMountDoom, 2208.0, "Another cleft."),
    HistoryEvent(Phase.raurosToMountDoom, 2214.5, "Still scrambling along back from the ridge."),
    HistoryEvent(Phase.raurosToMountDoom, 2219.3, "Reach the deepest ravine thus far – a rock fault. Far wall is “many fathoms high.” Frodo climbs down. Finds a few gnarled trees, mainly firs, but only for about 50 yards. Stumps continue to cliff edge. As cliff is lower, Frodo decides they should descend: the rock has “slipped and cracked.” Storm arrives just as Frodo starts down. He slithers down to a rock ledge below. Sam remembers his rope and pulls Frodo up. After the storm they use the rope to descend. Dusk falls."),
    HistoryEvent(Phase.raurosToMountDoom, 2220.9, "Head east from base of cliff, picking their way through wet boulders."),
    HistoryEvent(Phase.raurosToMountDoom, 2224.1, "Reach a great fissure with a stream inside. It curves north: bars way."),
    HistoryEvent(Phase.raurosToMountDoom, 2225.7, "Head back toward cliff, angling south. Too difficult to go far. No spot to hide. Stop next to a boulder. See Gollum crawling down cliff. Capture Gollum (ca. 8 p.m.). STOP, but have no rest while they watch Gollum. Late night, Frodo extracts pledge, then releases Gollum."),
    HistoryEvent(Phase.raurosToMountDoom, 2227.3, "Start again ca. 2 a.m. Gollum leads them back north."),
    HistoryEvent(Phase.raurosToMountDoom, 2232.2, "Reach the rift they had seen before, but farther north where sides are lower. Climb down into it (15 feet deep). Follow it south beside a “shallow stony stream.” Gollum recites ‘Fish’ riddle."),
    HistoryEvent(Phase.raurosToMountDoom, 2240.2, "Gully turns east, broadens and grows more shallow."),
    HistoryEvent(Phase.raurosToMountDoom, 2241.8, "Dawn. Camp in gully on a wide flat shelf of stone. Gully now only 6 feet deep. Frodo and Sam plan to watch, but both sleep."),
    HistoryEvent(Phase.raurosToMountDoom, 2242.0, "Set out when dark."),
    HistoryEvent(Phase.raurosToMountDoom, 2248.3, "Gully more shallow and less sloping."),
    HistoryEvent(Phase.raurosToMountDoom, 2254.7, "Gully bottom less rocky."),
    HistoryEvent(Phase.raurosToMountDoom, 2257.9, "Creek enters from north. Eat."),
    HistoryEvent(Phase.raurosToMountDoom, 2261.1, "Floor still more muddy. Sides dwindle to mere banks."),
    HistoryEvent(Phase.raurosToMountDoom, 2264.3, "Stream begins to wind. Sky grows cloudy."),
    HistoryEvent(Phase.raurosToMountDoom, 2267.6, "Banks reduced to mossy mounds."),
    HistoryEvent(Phase.raurosToMountDoom, 2270.8, "Stream gurgles over a stone shelf into the bog. Dry reeds all around. Mists rise above the Dead Marshes just ahead and on both sides. See Mountains of Mordor far ahead: wreathed in fog, lit by dawn. Rest briefly."),
    HistoryEvent(Phase.raurosToMountDoom, 2274.0, "Gollum’s path winds through the mists, turning to find the way between “pools, and soft mires.” No birds."),
    HistoryEvent(Phase.raurosToMountDoom, 2282.0, "As mists rise (ca. 10 a.m.), they stop for day in a reed-thicket."),
    HistoryEvent(Phase.raurosToMountDoom, 2282.2, "Late afternoon. Continue on."),
    HistoryEvent(Phase.raurosToMountDoom, 2286.9, "Enter the heart of the Dead Marshes."),
    HistoryEvent(Phase.raurosToMountDoom, 2291.7, "Round the west end of a wide stagnant mere. Air is “black and heavy to breathe.”"),
    HistoryEvent(Phase.raurosToMountDoom, 2294.9, "Wisps of lights begin to appear: “candles of corpses.” Another wide mere extends west from there."),
    HistoryEvent(Phase.raurosToMountDoom, 2296.5, "Sam falls, sees dead faces in the water (from Battle of the Last Alliance)."),
    HistoryEvent(Phase.raurosToMountDoom, 2298.1, "They almost crawl as they founder through the treacherous mire."),
    HistoryEvent(Phase.raurosToMountDoom, 2299.8, "Reach firmer ground (ca. 4 a.m.). Gollum trots down “a long lane between high reeds,” then stops and sniffs."),
    HistoryEvent(Phase.raurosToMountDoom, 2301.4, "Gollum’s uneasiness grows. Hear cry of Nazgûl. Rush of wind: lights go out. Moon peaks through clouds. See Nazgûl. Gollum cowers and refuses to go on until moon is low."),
    HistoryEvent(Phase.raurosToMountDoom, 2306.2, "Dawn. End of the marshes. Clear and cold. Mountains tower ahead across wastelands. Hide “under a black stone” during gray day."),
    HistoryEvent(Phase.raurosToMountDoom, 2306.4, "Leave when full dark."),
    HistoryEvent(Phase.raurosToMountDoom, 2307.8, "Cross area of dry peat, broken by flats of cracked, dry mud. Land slopes slowly east. Ring grows heavier. Sam’s mood darkens."),
    HistoryEvent(Phase.raurosToMountDoom, 2314.2, "Climb a long shallow slope."),
    HistoryEvent(Phase.raurosToMountDoom, 2322.3, "Gully curves away north, then west back to the marshes."),
    HistoryEvent(Phase.raurosToMountDoom, 2330.3, "Hide again during day."),
    HistoryEvent(Phase.raurosToMountDoom, 2330.5, "Creep forward as dark falls. Bitter, parched air. Unknown to them, Battle of Helm’s Deep rages far to the west."),
    HistoryEvent(Phase.raurosToMountDoom, 2333.5, "Land rises in a long slope: arid moors of the Noman-lands."),
    HistoryEvent(Phase.raurosToMountDoom, 2336.8, "Descend a steeper hill face."),
    HistoryEvent(Phase.raurosToMountDoom, 2343.2, "Land rises in another long slow climbing slope."),
    HistoryEvent(Phase.raurosToMountDoom, 2348.0, "Still on the moors."),
    HistoryEvent(Phase.raurosToMountDoom, 2354.5, "Descend a last hill face. Reach the Desolation of the Morannon: gasping pools, mounds of slag. Stop at first slag-heap, but fumes drive them away. Crawl into a “wide, almost circular pit, high-banked on the west.” An oily ooze fills bottom. Stay there."),
    HistoryEvent(Phase.raurosToMountDoom, 2354.6, "On waking, Sam hears Smeagol/Gollum’s debate. Sam wonders who ‘she’ is. At dusk, creep slowly forward."),
    HistoryEvent(Phase.raurosToMountDoom, 2357.7, "Nazgûl passes over. Pause for a while."),
    HistoryEvent(Phase.raurosToMountDoom, 2364.1, "Midnight. Nazgûl flies over again, but high up (on way to Isengard). Terrified, Gollum refuses to go on until ordered by Frodo."),
    HistoryEvent(Phase.raurosToMountDoom, 2373.8, "Dawn. Can see guards on the wall above the Black Gate. Hide in a hollow “delved in the side of a low hill.” See Army of Easterlings arrive, then later, an army of Southrons. Sam recites “Oliphaunt” poem. Gollum tells of ‘secret’ way. Frodo decides to follow Gollum south. Rest during day."),
    HistoryEvent(Phase.raurosToMountDoom, 2373.9, "Dusk. Creep out west side of hollow."),
    HistoryEvent(Phase.raurosToMountDoom, 2377.0, "Walk SW, west of the road. Road runs in a trenchlike valley between the mountains and the moors. It is newly repaired for many miles."),
    HistoryEvent(Phase.raurosToMountDoom, 2388.3, "End of the slag heaps. Brief rest. Midnight: Moon rises, almost full."),
    HistoryEvent(Phase.raurosToMountDoom, 2399.5, "Can still see the red light in one of the Towers of the Teeth."),
    HistoryEvent(Phase.raurosToMountDoom, 2409.2, "Finally turn south enough to hide the light from the Tower."),
    HistoryEvent(Phase.raurosToMountDoom, 2412.4, "Dawn. Reach northern edge of Ithilien. East across road are dark trees. Closer ‘a tumbled heathland’ with ‘knots of pine-trees.’ Air is fresh and fragrant. Hide in heather during day."),
    HistoryEvent(Phase.raurosToMountDoom, 2412.6, "Leave during twilight."),
    HistoryEvent(Phase.raurosToMountDoom, 2414.0, "Gollum leads them onto the road: straight and level. Go more quickly."),
    HistoryEvent(Phase.raurosToMountDoom, 2417.2, "In valley between mountains on east and steep slopes on west."),
    HistoryEvent(Phase.raurosToMountDoom, 2422.1, "Woods appear to the west. Some growth begins along the road edges."),
    HistoryEvent(Phase.raurosToMountDoom, 2426.9, "Road crosses stream on an arched masonry bridge."),
    HistoryEvent(Phase.raurosToMountDoom, 2434.9, "Road becomes more overgrown."),
    HistoryEvent(Phase.raurosToMountDoom, 2441.4, "Another stream is bridged."),
    HistoryEvent(Phase.raurosToMountDoom, 2444.6, "Reach north end of a long straight cutting through a stony ridge."),
    HistoryEvent(Phase.raurosToMountDoom, 2449.4, "Climb the west bank and go downhill. Follow a stream to a small clear pool. Bathe. Sam finds orc fire-ring."),
    HistoryEvent(Phase.raurosToMountDoom, 2451.0, "Camp back toward road. Gollum brings coneys. Sam cooks stew. Eat (8:30 a.m.). Found by Southern Rangers with Faramir. Gollum hides."),
    HistoryEvent(Phase.raurosToMountDoom, 2451.2, "Noon. Rangers battle the Haradrim. Sam sees an oliphaunt. Sleep to late afternoon. Faramir questions Frodo, then leads them west."),
    HistoryEvent(Phase.raurosToMountDoom, 2452.6, "Cross stream below the pool."),
    HistoryEvent(Phase.raurosToMountDoom, 2457.5, "Descend steep slope. Faramir and Frodo talk as they go."),
    HistoryEvent(Phase.raurosToMountDoom, 2460.7, "Thread their way through woodland."),
    HistoryEvent(Phase.raurosToMountDoom, 2465.5, "Trees grow thinner. Turn right and “come to a small river in a narrow gorge” – the same as that from the pool."),
    HistoryEvent(Phase.raurosToMountDoom, 2467.1, "Frodo and Sam are blindfolded and led down a steep path, then up to Henneth Annûn. Sunset gleams through the waterfall."),
    HistoryEvent(Phase.raurosToMountDoom, 2467.3, "Moonset. Gollum fishes in waterfall pool. With Frodo’s help, Faramir captures and questions Gollum. Rest a short time more while supplies are prepared. Leave ca. 8 a.m. Rangers lead them south, blindfolded."),
    HistoryEvent(Phase.raurosToMountDoom, 2468.7, "Faramir removes blindfolds. Advises them to follow upper edge of steep-falling lands to west."),
    HistoryEvent(Phase.raurosToMountDoom, 2478.4, "Cross a fast stream. Brief rest. Eat."),
    HistoryEvent(Phase.raurosToMountDoom, 2489.7, "Brief rest."),
    HistoryEvent(Phase.raurosToMountDoom, 2496.1, "Cross a tumbling stream."),
    HistoryEvent(Phase.raurosToMountDoom, 2502.5, "Nightfall. Sleep beneath an ancient tree. Sam restless."),
    HistoryEvent(Phase.raurosToMountDoom, 2502.7, "Leave at first light."),
    HistoryEvent(Phase.raurosToMountDoom, 2515.4, "Thicker trees. Brief rest. Air growing heavy. Gollum urges more speed."),
    HistoryEvent(Phase.raurosToMountDoom, 2525.1, "Cross a small stream."),
    HistoryEvent(Phase.raurosToMountDoom, 2528.3, "Reach area of large trees – more open: ash and oak. Gollum fearful."),
    HistoryEvent(Phase.raurosToMountDoom, 2537.9, "Dusk. End of the forest. Can see White Mountains to the west and dark peaks of the Ephel Dúath to the east. A vale falls away before them – the Morgul. Gollum wants to continue, but they stop until midnight. Perched in an oak, the hobbits cannot sleep."),
    HistoryEvent(Phase.raurosToMountDoom, 2538.1, "Just past midnight, head east. Land slopes up steeply. Thickets and brambles."),
    HistoryEvent(Phase.raurosToMountDoom, 2541.2, "Cross a deep cleft."),
    HistoryEvent(Phase.raurosToMountDoom, 2544.4, "Go around a dark pit."),
    HistoryEvent(Phase.raurosToMountDoom, 2547.6, "Go down a bit, but then up on a longer, steeper slope."),
    HistoryEvent(Phase.raurosToMountDoom, 2550.8, "Halt briefly. Can see tops of trees behind. Darkness begins to spread."),
    HistoryEvent(Phase.raurosToMountDoom, 2554.0, "Climb a great ‘hogback’ – climb the steep backslope, covered with spiny thickets. Descend the even steeper cliff face. Part way down, crawl into a ‘hollow hall’ formed by a “tangled knot of thorns.” Sleep."),
    HistoryEvent(Phase.raurosToMountDoom, 2554.2, "No dawn. Day grows even darker as time passes. Gollum wakes them (ca. 4 p.m.): “No time to lose.” Leads them down the hillside."),
    HistoryEvent(Phase.raurosToMountDoom, 2557.2, "Turn south across a long broken slope."),
    HistoryEvent(Phase.raurosToMountDoom, 2558.9, "Turn east and reach the Southward Road. Follow the road into a great ring of trees to the Cross-roads. The setting sun lights the fallen head of the statue of a King of Gondor."),
    HistoryEvent(Phase.raurosToMountDoom, 2560.5, "Pass east out of the trees, following the Morgul-road. Road climbs steeply, but is straight."),
    HistoryEvent(Phase.raurosToMountDoom, 2562.1, "At the top of a ‘flatiron’ the road cuts through the steep-faced drop and curves sharply south around a “great shoulder of rock.”."),
    HistoryEvent(Phase.raurosToMountDoom, 2563.7, "Road curves east again, next to the ravine of the Morgulduin. Way slants up steeply. Frodo glances across the vale and sees Minas Morgul."),
    HistoryEvent(Phase.raurosToMountDoom, 2564.5, "Come to the white bridge. The road crosses it and winds up to the city gates. All is rotten, cold. Frodo totters forward as if to cross the bridge, but Sam stops him. Gollum leads them back across the road to a gap in the stone wall – a path along the slopes north of the river."),
    HistoryEvent(Phase.raurosToMountDoom, 2566.1, "On a high shelf overlooking the city Frodo stops. The Morgul-host marches forth."),
    HistoryEvent(Phase.raurosToMountDoom, 2566.9, "Continue up path a short way. Reach bottom of the Straight Stair. Stair is cut into the cliff with walls on each side, steps narrow, uneven, and steep as a ladder."),
    HistoryEvent(Phase.raurosToMountDoom, 2567.7, "Above the stair, the cutting continues with a winding path – still climbing, but needs no steps: “seemed to go on for miles.”."),
    HistoryEvent(Phase.raurosToMountDoom, 2570.1, "Reach a wide shelf – cliff on left, chasm on right. No longer climbing. Ground is broken."),
    HistoryEvent(Phase.raurosToMountDoom, 2572.5, "Reach bottom of the Winding Stair. Stair zig-zigs up the sloping cliff. Even looks down on wraith-road at one point."),
    HistoryEvent(Phase.raurosToMountDoom, 2573.3, "Reach the top of the stairs. See red light through window in top of the Tower “a long way off.” Sleep there between two great piers of rock. All around are “jagged pinnacles...crevices and fissures.”."),
    HistoryEvent(Phase.raurosToMountDoom, 2573.5, "“Day.” Sam wakes and sees Gollum ‘pawing at’ Frodo. ‘Sneak’ conversation. Gollum leads them “up a long ravine between piers and columns of torn and weathered rocks.”."),
    HistoryEvent(Phase.raurosToMountDoom, 2575.0, "Opening to Shelob’s Lair. Tunnel is so high and wide that Frodo and Sam can’t touch hands as they feel their way along each wall. Tunnel climbs slowly."),
    HistoryEvent(Phase.raurosToMountDoom, 2576.6, "Sam feels an opening on the right."),
    HistoryEvent(Phase.raurosToMountDoom, 2578.2, "Sam feels an opening on the right."),
    HistoryEvent(Phase.raurosToMountDoom, 2579.8, "Frodo feels an opening on the left."),
    HistoryEvent(Phase.raurosToMountDoom, 2581.4, "Frodo and Sam’s senses become numb, but feel things hanging down."),
    HistoryEvent(Phase.raurosToMountDoom, 2583.0, "Sam leaves right wall and holds on to Frodo."),
    HistoryEvent(Phase.raurosToMountDoom, 2593.5, "Frodo finds opening to main pit on left."),
    HistoryEvent(Phase.raurosToMountDoom, 2593.9, "Tunnel forks. Left tunnel closed with a door. Realize Gollum is gone. Shelob appears. Use the Phial of Galadriel to drive off Shelob. Tunnel rises steeply to exit. Use Sting to cut webs."),
    HistoryEvent(Phase.raurosToMountDoom, 2594.3, "Frodo runs ahead and is stung by Shelob. Sam fights off Gollum and reaches Frodo and drives off Shelob, but is too late. Thinking Frodo dead, Sam reluctantly takes the Ring and continues on."),
    HistoryEvent(Phase.raurosToMountDoom, 2595.1, "Sam reaches base of a flight of shallow steps to the cleft."),
    HistoryEvent(Phase.raurosToMountDoom, 2595.9, "From the cleft of the Pass, Sam looks back. Hearing orcs, he puts on the Ring. When orcs reach Frodo, Sam rushes back."),
    HistoryEvent(Phase.raurosToMountDoom, 2596.0, "Frodo and Sam reach gate of the Tower ca. 5 a.m. Watchers send up signal of their escape. Run. Road curves out of sight from the gate."),
    HistoryEvent(Phase.raurosToMountDoom, 2597.5, "Road curves down sharply to meet the Morgul-road. At the bridge just beyond the road meeting, they jump. Land just a few feet below in a thorn thicket. Dawn – but dark in the valley."),
    HistoryEvent(Phase.raurosToMountDoom, 2599.1, "Climb down to bottom of north-running valley."),
    HistoryEvent(Phase.raurosToMountDoom, 2600.7, "Halt briefly. Sam falls asleep. Turn north in the ravine. Frodo discards chain mail. Sam wishes for light and water."),
    HistoryEvent(Phase.raurosToMountDoom, 2602.3, "Frodo senses Black Rider. Halt again. Sky brightens. See flight of fallen Witch King – ill news for Barad-dûr. Eat a bit."),
    HistoryEvent(Phase.raurosToMountDoom, 2603.9, "Cross over to path west of a dry stream bed. Valley rises slowly to north."),
    HistoryEvent(Phase.raurosToMountDoom, 2608.7, "Hear water trickling from gully on left."),
    HistoryEvent(Phase.raurosToMountDoom, 2618.4, "Road broadens and a rough wall begins: nearing an orc hold. Cross river-bed (a few pools in the bottom). Low scrubby trees. Midges."),
    HistoryEvent(Phase.raurosToMountDoom, 2620.0, "Climb up into a ravine. Hide in brambles. Frodo sleeps. Sam sees star and also sleeps."),
    HistoryEvent(Phase.raurosToMountDoom, 2620.2, "Continue up ravine until it disappears, then climb last 100 feet to the ridge."),
    HistoryEvent(Phase.raurosToMountDoom, 2623.2, "Ridge stands 1500 feet above the plain. Plain is crawling with enemies. See Mount Doom 40 miles away."),
    HistoryEvent(Phase.raurosToMountDoom, 2626.4, "Try to go north along ridge, but cannot. Retrace path back to valley floor. Stay east of water-course."),
    HistoryEvent(Phase.raurosToMountDoom, 2628.1, "See orc hold by path on west."),
    HistoryEvent(Phase.raurosToMountDoom, 2631.3, "Hear orc scouts. Hide behind bush. Learn news of Gollum. Light fades as they hide."),
    HistoryEvent(Phase.raurosToMountDoom, 2637.7, "Continue in the dark along eastern edge of the valley."),
    HistoryEvent(Phase.raurosToMountDoom, 2657.0, "Stagnant pool of water. Do not see it in the dark."),
    HistoryEvent(Phase.raurosToMountDoom, 2663.5, "Grey light – Hide and sleep."),
    HistoryEvent(Phase.raurosToMountDoom, 2663.6, "Eat. Finish Faramir’s food. When quite dark, begin again."),
    HistoryEvent(Phase.raurosToMountDoom, 2673.1, "Brief halt."),
    HistoryEvent(Phase.raurosToMountDoom, 2682.8, "Brief halt."),
    HistoryEvent(Phase.raurosToMountDoom, 2692.4, "Brief halt."),
    HistoryEvent(Phase.raurosToMountDoom, 2703.7, "At first light, hide in a hollow under an overhanging stone. Strong wind from west. Ahead the valley has climbed nearly to top of the inner ridge. Water course ends in broken steps of rock. Can see road from old castle of Durthang. Frodo sleeps. Sam finds water. Returns and sees Gollum. Wakes Frodo to watch. Sam sleeps."),
    HistoryEvent(Phase.raurosToMountDoom, 2703.9, "Light fading when wake. See watch fires on heights. Return to spring. Fill water bottle."),
    HistoryEvent(Phase.raurosToMountDoom, 2704.5, "Climb warily up to the road when it swings east."),
    HistoryEvent(Phase.raurosToMountDoom, 2718.2, "A side path runs south into Gorgoroth toward main road. Sheer drop from road becomes increasingly deep."),
    HistoryEvent(Phase.raurosToMountDoom, 2723.0, "Road bends a little north and hides view from west. Rest. Orc company sees them, assumes they are deserters. Frodo and Sam are forced to join march."),
    HistoryEvent(Phase.raurosToMountDoom, 2729.4, "Road runs down a long slope into the plain. Frodo starts to stumble."),
    HistoryEvent(Phase.raurosToMountDoom, 2732.7, "Out on the plain, drawing near Isenmouthe: Road-meeting."),
    HistoryEvent(Phase.raurosToMountDoom, 2735.9, "In confusion of several companies meeting, Sam pulls Frodo with him, crawling across the road and over the curb. Crawl 20 yards to a shallow pit and sleep (late night to early morning). Cold."),
    HistoryEvent(Phase.raurosToMountDoom, 2736.0, "Morning. Sam sees Gorgoroth is pitted with great holes. Roads are empty. Crawl from hollow to hollow slanting toward the foothills to north."),
    HistoryEvent(Phase.raurosToMountDoom, 2742.3, "Halt. Sam decides they should go back to road."),
    HistoryEvent(Phase.raurosToMountDoom, 2743.9, "Climb onto the causeway."),
    HistoryEvent(Phase.raurosToMountDoom, 2747.2, "Walk east along the road as it skirts the Ash Mountains. See no one."),
    HistoryEvent(Phase.raurosToMountDoom, 2752.0, "Camp just off the road."),
    HistoryEvent(Phase.raurosToMountDoom, 2752.1, "Return to road. Trudge east."),
    HistoryEvent(Phase.raurosToMountDoom, 2758.4, "Rest."),
    HistoryEvent(Phase.raurosToMountDoom, 2764.9, "Find cistern, but it is empty. Eat and rest."),
    HistoryEvent(Phase.raurosToMountDoom, 2771.3, "Rest."),
    HistoryEvent(Phase.raurosToMountDoom, 2776.1, "Camp just off road. Hear troops at night."),
    HistoryEvent(Phase.raurosToMountDoom, 2776.3, "Return to road. More and more Frodo is bowed down by the Ring."),
    HistoryEvent(Phase.raurosToMountDoom, 2782.6, "Rest."),
    HistoryEvent(Phase.raurosToMountDoom, 2789.0, "Find cistern with muddied water in bottom. Drink and fill bottle. Eat."),
    HistoryEvent(Phase.raurosToMountDoom, 2795.4, "Rest."),
    HistoryEvent(Phase.raurosToMountDoom, 2800.3, "Camp just off road. Hear horse-messenger gallop by during night."),
    HistoryEvent(Phase.raurosToMountDoom, 2800.4, "Return to road. Frodo ceases to speak. Stumbles as he fights Ring."),
    HistoryEvent(Phase.raurosToMountDoom, 2806.7, "Rest."),
    HistoryEvent(Phase.raurosToMountDoom, 2811.5, "Stop to eat. Mount Doom is due south. Leave road and turn toward it."),
    HistoryEvent(Phase.raurosToMountDoom, 2818.0, "Rest."),
    HistoryEvent(Phase.raurosToMountDoom, 2824.4, "The Dreadful Nightfall. Only half bottle of water left. Frodo sleeps fitfully, and Sam, very little. He sees gleam of Gollum’s eyes."),
    HistoryEvent(Phase.raurosToMountDoom, 2824.6, "Wake in dim light of dawn. Discard everything they do not need."),
    HistoryEvent(Phase.raurosToMountDoom, 2830.8, "Rest. No attempt at concealment. Frodo goes faster than Sam hoped."),
    HistoryEvent(Phase.raurosToMountDoom, 2835.7, "Rest."),
    HistoryEvent(Phase.raurosToMountDoom, 2840.5, "Extra effort squanders Frodo’s last strength. Sam cannot sleep. Argues with self. Ground trembles."),
    HistoryEvent(Phase.raurosToMountDoom, 2840.7, "Continue on in dark light. No water. Sam’s mouth too parched to eat."),
    HistoryEvent(Phase.raurosToMountDoom, 2845.3, "Rest."),
    HistoryEvent(Phase.raurosToMountDoom, 2848.5, "Rest. Fumes grow worse. Some wind from the west."),
    HistoryEvent(Phase.raurosToMountDoom, 2851.8, "Rest."),
    HistoryEvent(Phase.raurosToMountDoom, 2856.6, "Continue to foot of Mount Doom. Sam tries to warm Frodo as he sleeps."),
    HistoryEvent(Phase.raurosToMountDoom, 2856.7, "As attempt to start, Frodo falls and begins to crawl. Sam carries him."),
    HistoryEvent(Phase.raurosToMountDoom, 2858.2, "Stop more than half way up base of the mountain. Rest."),
    HistoryEvent(Phase.raurosToMountDoom, 2859.8, "Sam and Frodo both crawl up slope to Sauron’s Road. Frodo turns east and see the Eye: falls. Sam carries him again."),
    HistoryEvent(Phase.raurosToMountDoom, 2861.4, "Gollum attacks! Sam fights Gollum. Frodo goes ahead."),
    HistoryEvent(Phase.raurosToMountDoom, 2862.2, "Frodo enters the Door to the Sammath Naur."),
    HistoryEvent(Phase.raurosToMountDoom, 2863.0, "Frodo claims the Ring just as Sam finds him. Gollum attacks again, bites Ring from Frodo’s finger and falls into lava. Ring Destroyed. Barad-dûr and Morannon collapse."),
    HistoryEvent(Phase.raurosToMountDoom, 2863.8, "Sam carries Frodo back outside. They see destruction all around."),
    HistoryEvent(Phase.raurosToMountDoom, 2867.0, "As they go down the road, smoke and steam belch from the mountain. Reach an ash hill and climb to the top. Are cut off from going further. Both fall."),
    HistoryEvent(Phase.raurosToMountDoom, 2887.2, "Eagles rescue Frodo and Sam and carry them to the Morannon."),
  ];
}