import '../history_event.dart';
import '../phase.dart';

class RivendellToBagEnd {
  final events = [
    HistoryEvent(Phase.rivendellToBagEnd, 4863.6, "Leave the Last Homely House – mid-morning. Cold."),
    HistoryEvent(Phase.rivendellToBagEnd, 4865.0, "Climb out of the valley of Rivendell. Ride slowly."),
    HistoryEvent(Phase.rivendellToBagEnd, 4874.7, "Camp northeast of the Ford of Bruinen."),
    HistoryEvent(Phase.rivendellToBagEnd, 4874.9, "Continue slowly."),
    HistoryEvent(Phase.rivendellToBagEnd, 4876.3, "Reach the Ford. Frodo hesitates to cross. He is in pain: anniversary of his wounding on Weathertop. Continue across the Ford."),
    HistoryEvent(Phase.rivendellToBagEnd, 4877.9, "Road climbs through a cutting of red stone topped with tall pines."),
    HistoryEvent(Phase.rivendellToBagEnd, 4882.7, "Road continues gently uphill. Much grass on sides. Hills on the north."),
    HistoryEvent(Phase.rivendellToBagEnd, 4890.8, "Camp south side of road."),
    HistoryEvent(Phase.rivendellToBagEnd, 4891.0, "Continue west-southwest along road, riding slowly. Frodo still ill."),
    HistoryEvent(Phase.rivendellToBagEnd, 4894.0, "Cross a small stream. Road bends more SW, skirting the feet of the Trollshaws. The steep ravine of the Bruinen also runs WSW not far S."),
    HistoryEvent(Phase.rivendellToBagEnd, 4898.8, "Eat. Frodo begins to feel better."),
    HistoryEvent(Phase.rivendellToBagEnd, 4906.9, "Camp near a valley from the north."),
    HistoryEvent(Phase.rivendellToBagEnd, 4907.1, "Leave after a leisurely breakfast."),
    HistoryEvent(Phase.rivendellToBagEnd, 4910.1, "Bruinen turns more to the south."),
    HistoryEvent(Phase.rivendellToBagEnd, 4914.9, "Eat. Rest. Can see ruins on hilltop to the north."),
    HistoryEvent(Phase.rivendellToBagEnd, 4923.0, "Camp near a valley from the north."),
    HistoryEvent(Phase.rivendellToBagEnd, 4923.1, "Road now runs due west."),
    HistoryEvent(Phase.rivendellToBagEnd, 4931.0, "Eat below out-thrust ‘toe’ of a hill."),
    HistoryEvent(Phase.rivendellToBagEnd, 4939.1, "Camp. Wander in autumn woods which run into the valley on the north."),
    HistoryEvent(Phase.rivendellToBagEnd, 4939.2, "Continue west on road through woods."),
    HistoryEvent(Phase.rivendellToBagEnd, 4942.3, "Leave woods."),
    HistoryEvent(Phase.rivendellToBagEnd, 4947.1, "Eat."),
    HistoryEvent(Phase.rivendellToBagEnd, 4955.2, "Camp. Still warm."),
    HistoryEvent(Phase.rivendellToBagEnd, 4955.3, "Road now turns northwest. Still skirts hills."),
    HistoryEvent(Phase.rivendellToBagEnd, 4956.8, "Reach pathway to Stone Trolls. Sam tells Frodo what happened there."),
    HistoryEvent(Phase.rivendellToBagEnd, 4956.9, "Eat. Continue northwest on the road."),
    HistoryEvent(Phase.rivendellToBagEnd, 4963.2, "Road climbs over an out-thrust hill from north. Hills now also south of road with valleys running SW to Hoarwell."),
    HistoryEvent(Phase.rivendellToBagEnd, 4968.0, "Reach hillcrest. Can see Hoarwell below."),
    HistoryEvent(Phase.rivendellToBagEnd, 4971.3, "Ruins on hilltop north of road. Camp in a SW-running valley."),
    HistoryEvent(Phase.rivendellToBagEnd, 4971.4, "Road rounds ‘toe’ of a hill from the north: the end of the Trollshaws."),
    HistoryEvent(Phase.rivendellToBagEnd, 4977.7, "Pass point where Strider led them north from road (exactly 1 year ago)."),
    HistoryEvent(Phase.rivendellToBagEnd, 4979.3, "Cross The Last Bridge. Road now turns more to the west. Eat."),
    HistoryEvent(Phase.rivendellToBagEnd, 4982.5, "Reach northeast end of valley which they had followed from Weathertop. They pass by and continue WNW on the road into the Lone-lands."),
    HistoryEvent(Phase.rivendellToBagEnd, 4987.4, "Weather still fair. Camp."),
    HistoryEvent(Phase.rivendellToBagEnd, 4987.5, "Road swings northwest through open country. South of the road are bushes and stunted trees: wild and pathless. Ride now more quickly."),
    HistoryEvent(Phase.rivendellToBagEnd, 5011.5, "Camp."),
    HistoryEvent(Phase.rivendellToBagEnd, 5011.7, "Road curves more to west. Open country. No streams"),
    HistoryEvent(Phase.rivendellToBagEnd, 5035.6, "Camp."),
    HistoryEvent(Phase.rivendellToBagEnd, 5035.8, "Continue west. Far ahead begin to see tops of the Weather Hills."),
    HistoryEvent(Phase.rivendellToBagEnd, 5059.8, "Camp."),
    HistoryEvent(Phase.rivendellToBagEnd, 5059.9, "Continue west on road."),
    HistoryEvent(Phase.rivendellToBagEnd, 5071.0, "Weather hills slowly rise on the horizon."),
    HistoryEvent(Phase.rivendellToBagEnd, 5083.9, "Camp"),
    HistoryEvent(Phase.rivendellToBagEnd, 5084.1, "Continue west."),
    HistoryEvent(Phase.rivendellToBagEnd, 5092.0, "Road turns slightly to the south. Hills now are more prominent."),
    HistoryEvent(Phase.rivendellToBagEnd, 5108.1, "Camp."),
    HistoryEvent(Phase.rivendellToBagEnd, 5108.2, "Road now runs southwest. Weathertop becomes visible straight ahead."),
    HistoryEvent(Phase.rivendellToBagEnd, 5132.2, "Camp. Weather still is warm and clear."),
    HistoryEvent(Phase.rivendellToBagEnd, 5132.4, "Road continues southwest. Land rises slowly toward Hills."),
    HistoryEvent(Phase.rivendellToBagEnd, 5156.3, "Camp. Weathertop lies just south of due west."),
    HistoryEvent(Phase.rivendellToBagEnd, 5156.5, "Hurry along the road."),
    HistoryEvent(Phase.rivendellToBagEnd, 5164.4, "Pass the first foothills below Weathertop."),
    HistoryEvent(Phase.rivendellToBagEnd, 5172.4, "Road reaches southeastern foot of Weathertop. Eat in haste."),
    HistoryEvent(Phase.rivendellToBagEnd, 5180.5, "Weathertop immediately north of road. Frodo refuses to look at it. As the shadows lengthen, they continue hurriedly past."),
    HistoryEvent(Phase.rivendellToBagEnd, 5188.5, "Camp. Weather turns damp and cold."),
    HistoryEvent(Phase.rivendellToBagEnd, 5188.7, "Road continues south to swing south of the Midgewater Marshes."),
    HistoryEvent(Phase.rivendellToBagEnd, 5196.6, "Weather turns wet and cold."),
    HistoryEvent(Phase.rivendellToBagEnd, 5204.6, "Land now slopes slowly downhill, away from Weathertop."),
    HistoryEvent(Phase.rivendellToBagEnd, 5212.7, "Camp. Damp and cold."),
    HistoryEvent(Phase.rivendellToBagEnd, 5212.8, "Road continues southwest and slowly downhill."),
    HistoryEvent(Phase.rivendellToBagEnd, 5236.8, "Reach the southeast edge of the Midgewater Marshes."),
    HistoryEvent(Phase.rivendellToBagEnd, 5237.0, "Road curves west around southern edge of the Marshes."),
    HistoryEvent(Phase.rivendellToBagEnd, 5252.9, "Drizzly all day. Ride a bit more quickly."),
    HistoryEvent(Phase.rivendellToBagEnd, 5262.6, "Camp due south of the Marshes."),
    HistoryEvent(Phase.rivendellToBagEnd, 5262.7, "Road curves slightly north of west. Marshes fill all the northern horizon."),
    HistoryEvent(Phase.rivendellToBagEnd, 5288.3, "Camp. Marshes farther north from the road."),
    HistoryEvent(Phase.rivendellToBagEnd, 5288.5, "Road continues west-northwest."),
    HistoryEvent(Phase.rivendellToBagEnd, 5301.2, "Can see western edge of the Marshes through the misty rain."),
    HistoryEvent(Phase.rivendellToBagEnd, 5314.1, "Still drizzly. Camp."),
    HistoryEvent(Phase.rivendellToBagEnd, 5314.2, "Road continues west-northwest. Rises slightly uphill."),
    HistoryEvent(Phase.rivendellToBagEnd, 5323.7, "Begin to see the Chetwood in distance ahead. Dark through the rain."),
    HistoryEvent(Phase.rivendellToBagEnd, 5330.1, "Rain becomes heavy. West wind. Reach the south edge of the Chetwood. Trees nearly barren."),
    HistoryEvent(Phase.rivendellToBagEnd, 5339.8, "Camp in stables of The Forsaken Inn: inn now closed. Rains all night."),
    HistoryEvent(Phase.rivendellToBagEnd, 5340.0, "Continue NW toward Bree. Bree-hill is hidden in the “curtain of rain.”."),
    HistoryEvent(Phase.rivendellToBagEnd, 5347.9, "Continue uphill along road next to the heart of the Chetwood."),
    HistoryEvent(Phase.rivendellToBagEnd, 5355.9, "Pass spot where Strider had led them north from the road."),
    HistoryEvent(Phase.rivendellToBagEnd, 5363.9, "Reach the South-gate of Bree: Locked. Have to call many times."),
    HistoryEvent(Phase.rivendellToBagEnd, 5365.6, "Bree – Arrive at The Prancing Pony. Talk with Butterbur. Sam learns ‘Bill the Pony’ has returned. Stay at the Inn."),
    HistoryEvent(Phase.rivendellToBagEnd, 5365.7, "Spend the day at The Prancing Pony in Bree"),
    HistoryEvent(Phase.rivendellToBagEnd, 5365.9, "Leave Bree very early. Still raining. Bree-folk see them off."),
    HistoryEvent(Phase.rivendellToBagEnd, 5372.0, "Gandalf turns south to visit Tom Bombadil. Ride on as fast as possible."),
    HistoryEvent(Phase.rivendellToBagEnd, 5391.3, "The Old Forest begins to the south, but is hidden in the rain."),
    HistoryEvent(Phase.rivendellToBagEnd, 5404.2, "Hobbits continue on at a fast pace. Forest is now quite close, but still hidden in the rain.Sunset makes the ride even darker."),
    HistoryEvent(Phase.rivendellToBagEnd, 5413.8, "Sunset makes the ride even darker."),
    HistoryEvent(Phase.rivendellToBagEnd, 5429.9, "Reach the Brandywine Bridge late in the evening. Gates bar the way. When refused entry, Merry and Pippin climb the gate. Confront Bill Ferny. Spend the night in the Bridge-house with Shirriffs."),
    HistoryEvent(Phase.rivendellToBagEnd, 5430.1, "Decide to go straight to Hobbiton. Go west on the Road. Grey, but calm."),
    HistoryEvent(Phase.rivendellToBagEnd, 5446.0, "See smoke rising several places, especially in Woody End to the south."),
    HistoryEvent(Phase.rivendellToBagEnd, 5465.3, "Frogmorton: Shirriffs ‘arrest’ Frodo and friends. Stay at Shirriff-house."),
    HistoryEvent(Phase.rivendellToBagEnd, 5465.5, "10:00 a.m. Leave for Bywater. Merry makes Shirriffs march in front."),
    HistoryEvent(Phase.rivendellToBagEnd, 5475.0, "Noon. Rest."),
    HistoryEvent(Phase.rivendellToBagEnd, 5487.9, "Three-Farthing Stone (ca. 3 p.m.). Frodo and friends leave Shirriffs behind."),
    HistoryEvent(Phase.rivendellToBagEnd, 5491.1, "Turn NW on Bywater Road. High banks with hedges rise on each side."),
    HistoryEvent(Phase.rivendellToBagEnd, 5494.3, "Reach Bywater in late afternoon. All houses shut. Meet ruffians at west end of town. When confronted by Merry, Pippin and Sam, ruffians run. Merry blows the horn of Rohan, rallies hobbits. Pippin heads to Tookland to gather support. Merry sets trap: first Battle of Bywater. Frodo, Sam and Merry spend night with Farmer Cotton."),
    HistoryEvent(Phase.rivendellToBagEnd, 5494.5, "Eat late lunch at Cottons, then leave for Hobbiton."),
    HistoryEvent(Phase.rivendellToBagEnd, 5497.5, "Go west along Hobbiton Road. All trees felled along the road."),
    HistoryEvent(Phase.rivendellToBagEnd, 5500.7, "Reach bridge. Turn north across the Water. Much destroyed in Hobbiton. Can see the Hill ahead. Party Tree has been cut down."),
    HistoryEvent(Phase.rivendellToBagEnd, 5502.3, "Reach Bag End with a large party of hobbits. Frodo confronts Saruman. Wormtongue slays Saruman, and is killed by hobbits. End of the War of the Ring."),
  ];
}