import 'package:fantasy_odyssey/Models/history_event.dart';
import 'package:fantasy_odyssey/Models/phase.dart';

class RivendellToLothlorien {
  final events = [
    HistoryEvent(Phase.rivendellToLothlorien, 737.2, "Leave Rivendell at dusk."),
    HistoryEvent(Phase.rivendellToLothlorien, 738.7, "Climb out of the valley onto the moors."),
    HistoryEvent(Phase.rivendellToLothlorien, 750.0, "At the Ford of Brúinen, turn south on ‘narrow paths among folded lands’."),
    HistoryEvent(Phase.rivendellToLothlorien, 766.0, "To the west the Bruinen cuts a steep-sided canyon."),
    HistoryEvent(Phase.rivendellToLothlorien, 772.5, "Walk until dawn. Camp during the day."),
    HistoryEvent(Phase.rivendellToLothlorien, 774.9, "Empty country - rough and barren."),
    HistoryEvent(Phase.rivendellToLothlorien, 778.9, "Cross a small stream."),
    HistoryEvent(Phase.rivendellToLothlorien, 787.8, "Empty country - rough and barren."),
    HistoryEvent(Phase.rivendellToLothlorien, 796.6, "Camp in a hollow during the day."),
    HistoryEvent(Phase.rivendellToLothlorien, 811.1, "Crest the top of a hill. Snowcapped peak lies due east."),
    HistoryEvent(Phase.rivendellToLothlorien, 820.8, "Cold and windy. Camp during the day."),
    HistoryEvent(Phase.rivendellToLothlorien, 830.4, "Reach a small stream. Follow it west."),
    HistoryEvent(Phase.rivendellToLothlorien, 833.6, "Leave streambed."),
    HistoryEvent(Phase.rivendellToLothlorien, 844.9, "Paths few and winding. Camp during the day."),
    HistoryEvent(Phase.rivendellToLothlorien, 849.7, "After reaching the top of a rise, angle southeast."),
    HistoryEvent(Phase.rivendellToLothlorien, 869.0, "Camp in a thicket of thorn bushes during the day."),
    HistoryEvent(Phase.rivendellToLothlorien, 875.5, "Reach crest of another low mountain spur. Turn southwest as they descend."),
    HistoryEvent(Phase.rivendellToLothlorien, 881.9, "Path comes to a steep drop-off. Go along cliff-top for a while."),
    HistoryEvent(Phase.rivendellToLothlorien, 893.2, "Camp during the day."),
    HistoryEvent(Phase.rivendellToLothlorien, 901.2, "Cross a small stream."),
    HistoryEvent(Phase.rivendellToLothlorien, 917.3, "Camp during the day."),
    HistoryEvent(Phase.rivendellToLothlorien, 930.2, "Another snowcapped peak lies to the east."),
    HistoryEvent(Phase.rivendellToLothlorien, 941.5, "Camp during the day."),
    HistoryEvent(Phase.rivendellToLothlorien, 946.3, "Cross a small stream. It flows west into a swampy area."),
    HistoryEvent(Phase.rivendellToLothlorien, 965.6, "Camp during the day. Continues cold, gray and windy."),
    HistoryEvent(Phase.rivendellToLothlorien, 978.5, "After reaching a hilltop, turn southeast."),
    HistoryEvent(Phase.rivendellToLothlorien, 989.7, "Camp during the day."),
    HistoryEvent(Phase.rivendellToLothlorien, 1009.1, "Cross a small stream."),
    HistoryEvent(Phase.rivendellToLothlorien, 1013.9, "Camp during the day."),
    HistoryEvent(Phase.rivendellToLothlorien, 1026.8, "Rolling lands."),
    HistoryEvent(Phase.rivendellToLothlorien, 1038.0, "Camp during the day."),
    HistoryEvent(Phase.rivendellToLothlorien, 1062.2, "Camp during the day."),
    HistoryEvent(Phase.rivendellToLothlorien, 1075.0, "Land drops more steeply. Go southeast into a valley."),
    HistoryEvent(Phase.rivendellToLothlorien, 1086.3, "Cross a small stream. Camp during the day."),
    HistoryEvent(Phase.rivendellToLothlorien, 1091.1, "Weather warmer and sunny. Can see Mts. of Moria in distance. Eerily quiet."),
    HistoryEvent(Phase.rivendellToLothlorien, 1104.0, "Begin climb up north side of Hollin Ridge."),
    HistoryEvent(Phase.rivendellToLothlorien, 1110.4, "Reach Hollin Ridge. Large holly trees mark ridge. Day camp on Hollin Ridge. They plan to stay overnight, but after the crebain fly over, they leave at dusk."),
    HistoryEvent(Phase.rivendellToLothlorien, 1112.1, "Soon strike a good path that goes southeast toward the mountain pass. Path is lined with stones. Full moon."),
    HistoryEvent(Phase.rivendellToLothlorien, 1136.2, "Frodo and Gandalf sense something flying over just before dawn."),
    HistoryEvent(Phase.rivendellToLothlorien, 1139.4, "Cross a small stream. Camp during day of Jan. 9. Sunny, but colder."),
    HistoryEvent(Phase.rivendellToLothlorien, 1142.6, "Road begins climbing as it winds into the hills. Mountains are closer."),
    HistoryEvent(Phase.rivendellToLothlorien, 1166.8, "Camp during day."),
    HistoryEvent(Phase.rivendellToLothlorien, 1179.6, "Road climbs still higher."),
    HistoryEvent(Phase.rivendellToLothlorien, 1194.1, "Almost to the feet of the Redhorn. Camp during day of Jan. 11. Gandalf and Aragorn debate path. Wind turns NW. Black clouds form during afternoon."),
    HistoryEvent(Phase.rivendellToLothlorien, 1194.3, "Leave camp at dusk. (ca. 5 p.m.). Fearing snow, each takes wood along."),
    HistoryEvent(Phase.rivendellToLothlorien, 1197.4, "Path is fairly smooth. They make good time."),
    HistoryEvent(Phase.rivendellToLothlorien, 1200.6, "Path becomes more steep and is dotted with fallen stones."),
    HistoryEvent(Phase.rivendellToLothlorien, 1203.8, "Path climbs a sharp slope: cliff on left, drop-off on right. Begins to snow as reach a ‘shelf’ at the top of the slope."),
    HistoryEvent(Phase.rivendellToLothlorien, 1205.4, "Snow begins to fall more thickly."),
    HistoryEvent(Phase.rivendellToLothlorien, 1206.2, "They stop briefly. Wind slackens. Snow lessens. Start again (ca. 8 p.m.)."),
    HistoryEvent(Phase.rivendellToLothlorien, 1207.0, "Redhorn Pass. Snow becomes even heavier. Wind howls. Decide they can go no further. All huddle against the south-facing cliff, some behind Bill the Pony. Build fire. Stay until dawn."),
    HistoryEvent(Phase.rivendellToLothlorien, 1207.2, "Aragorn and Boromir start down, plowing through the snow."),
    HistoryEvent(Phase.rivendellToLothlorien, 1207.8, "Fellowship reaches great drift of snow. Clouds begin to break."),
    HistoryEvent(Phase.rivendellToLothlorien, 1208.6, "Snow steadily more shallow."),
    HistoryEvent(Phase.rivendellToLothlorien, 1210.2, "Back to shelf of stone ... no more snow (ca. 10:30 a.m.)."),
    HistoryEvent(Phase.rivendellToLothlorien, 1213.4, "Turn west, away from path they took up to the Pass. Crebain return."),
    HistoryEvent(Phase.rivendellToLothlorien, 1236.0, "Turn more southwest around foothills of the Silvertine."),
    HistoryEvent(Phase.rivendellToLothlorien, 1252.1, "Stop to eat (ca.6 p.m.), camp, and debate. Cold wind. Hear Wargs! Climb to top of the hill above them. Enter a ring of stones with gnarled trees within. Wargs gather. Attack just before dawn."),
    HistoryEvent(Phase.rivendellToLothlorien, 1252.2, "Leave ca. 8 a.m. Head south-southeast toward the Sirannon."),
    HistoryEvent(Phase.rivendellToLothlorien, 1260.1, "A barren country of red stones."),
    HistoryEvent(Phase.rivendellToLothlorien, 1268.2, "Reach the Sirannon (ca. 11 a.m.). Dry. Head east on a path along stream."),
    HistoryEvent(Phase.rivendellToLothlorien, 1271.4, "Path lies in a deep trough. It is a rough, winding track."),
    HistoryEvent(Phase.rivendellToLothlorien, 1274.6, "Stop to EAT quickly (ca. 12:30 - 1 p.m.)."),
    HistoryEvent(Phase.rivendellToLothlorien, 1281.8, "Fall of the Sirannon: Frodo, Gimli and Gandalf climb stairs to upland valley; return."),
    HistoryEvent(Phase.rivendellToLothlorien, 1282.6, "Climb curving road to upland valley. Most is filled with a lake."),
    HistoryEvent(Phase.rivendellToLothlorien, 1283.1, "Wade through stream at north end of lake."),
    HistoryEvent(Phase.rivendellToLothlorien, 1284.3, "Reach the Doors of Moria. (ca. 6 p.m.). Release Bill. Spend ca. ½ hour at Gate seeking the password. ATTACK by the Watcher in the Water."),
    HistoryEvent(Phase.rivendellToLothlorien, 1284.4, "Stop just inside Moria to eat and rest briefly. Leave ca. 7 p.m."),
    HistoryEvent(Phase.rivendellToLothlorien, 1289.1, "Frodo begins to hear Gollum’s pattering footsteps."),
    HistoryEvent(Phase.rivendellToLothlorien, 1293.9, "Stop to decide which path; brief halt."),
    HistoryEvent(Phase.rivendellToLothlorien, 1300.3, "Have to jump narrow fissure."),
    HistoryEvent(Phase.rivendellToLothlorien, 1305.2, "Have to jump 7 foot fissure; brief halt."),
    HistoryEvent(Phase.rivendellToLothlorien, 1316.4, "Reach junction of 3 passages, with Guardroom (ca. 1 a.m.). CAMP."),
    HistoryEvent(Phase.rivendellToLothlorien, 1316.6, "Leave Guardroom (ca. 8 a.m.). Take right hand passage."),
    HistoryEvent(Phase.rivendellToLothlorien, 1324.5, "Road climbs in great mounting curves with no side passages. (Est.) break."),
    HistoryEvent(Phase.rivendellToLothlorien, 1332.5, "(Est.) lunch and rest."),
    HistoryEvent(Phase.rivendellToLothlorien, 1340.6, "(Est.) break."),
    HistoryEvent(Phase.rivendellToLothlorien, 1348.6, "Reach the 21st Hall of the North End. Camp overnight."),
    HistoryEvent(Phase.rivendellToLothlorien, 1348.8, "(ca. 8 a.m.) Eat. Enter Chamber of Records nearby. Find Balin’s Tomb. ATTACK - orcs and cave troll. Escape through east door of room."),
    HistoryEvent(Phase.rivendellToLothlorien, 1350.2, "After descending 7 flights of stairs, REST."),
    HistoryEvent(Phase.rivendellToLothlorien, 1350.7, "Reach the 1st Deep. Fire blocks them from Orcs. Cross Bridge over Durin’s Deep. Balrog attacks. Gandalf and Balrog fall."),
    HistoryEvent(Phase.rivendellToLothlorien, 1351.0, "Rest escape up flight of steps, and out East Gate. Orcs flee. (ca.1 p.m.)."),
    HistoryEvent(Phase.rivendellToLothlorien, 1351.8, "STOP to vent grief. Then continue down rough, winding trail."),
    HistoryEvent(Phase.rivendellToLothlorien, 1354.3, "Durin’s Stone and Mirrormere. Stop briefly, then continue south on road."),
    HistoryEvent(Phase.rivendellToLothlorien, 1355.1, "Pause at the spring of the Silverlode."),
    HistoryEvent(Phase.rivendellToLothlorien, 1364.7, "Frodo and Sam lag behind. Aragorn and Boromir carry them to a dell nearby. Eat and rest (ca. 3 to 4 p.m.)."),
    HistoryEvent(Phase.rivendellToLothlorien, 1369.6, "Dusk (ca. 5 p.m.)."),
    HistoryEvent(Phase.rivendellToLothlorien, 1374.4, "Frodo begins to hear Gollum again, and sees glowing eyes."),
    HistoryEvent(Phase.rivendellToLothlorien, 1376.0, "Enter woods of Lothlórien."),
    HistoryEvent(Phase.rivendellToLothlorien, 1377.6, "Cross the Nimrodel. Go west upstream a short distance. Meet elves. Sleep on flets in the trees. Orc company passes during the night. Gollum appears briefly."),
    HistoryEvent(Phase.rivendellToLothlorien, 1377.8, "Start about 8 a.m. Clear and cold “like a cool summer day.” Follow path south beside the Silverlode."),
    HistoryEvent(Phase.rivendellToLothlorien, 1385.6, "Cross the Silverlode on ropes. Fellowship is blindfolded. Frodo notices paths are smooth, and he smells the trees and grass."),
    HistoryEvent(Phase.rivendellToLothlorien, 1417.8, "Pass through an open glade."),
    HistoryEvent(Phase.rivendellToLothlorien, 1429.1, "CAMP - Sleep on the ground. Still blindfolded."),
    HistoryEvent(Phase.rivendellToLothlorien, 1429.3, "Continue on path."),
    HistoryEvent(Phase.rivendellToLothlorien, 1458.1, "Noon - In a clearing, meet an elf-company. Blindfolds are removed.Climb to the top of the hill of Cerin Amroth. Can see all around. Stay there ca. 2 hours."),
    HistoryEvent(Phase.rivendellToLothlorien, 1470.9, "Elves light lanterns (ca. 5:30 p.m.)."),
    HistoryEvent(Phase.rivendellToLothlorien, 1474.2, "Reach the north side of Caras Galadan. Early stars are out (ca. 6:10 p.m.)."),
    HistoryEvent(Phase.rivendellToLothlorien, 1480.6, "Reach Gates of Caras Galadan (south side) and climb to meet Celeborn and Galadriel. Stay in Lothlórien for a month."),
  ];
}